<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'ebay_config_producttemplate__field__template.name__label'} = 'Template produit';
MLI18n::gi()->{'ebay_config_producttemplate__field__template.name__help'} = '<dl>
						<dt>Nom du produit sur eBay </dt>
<dd>Saisissez dans ce champ le nom de l’article, tel que vous voulez qu’il apparaisse sur votre page eBay. <br>
Le champ <b>#TITLE#</b> sera automatiquement remplacé par le nom que vous avez saisi.</dd>
			</dl>';
MLI18n::gi()->{'orderstatus_carrier_default_send_order_carrier'} = 'Transporter l\'ordre de passage';