<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Bepado_Productlist_Cell_aPreparedStatus__OK__title'} = 'Préparés avec succès';
MLI18n::gi()->{'Bepado_Productlist_Cell_aPreparedStatus__ERROR__title'} = 'Mal préparés';
MLI18n::gi()->{'Bepado_Productlist_Cell_aPreparedStatus__OPEN__title'} = 'Préparation non vérifiée';
MLI18n::gi()->{'Bepado_Productlist_Filter_aPreparedStatus__OK'} = 'Préparés avec succès';
MLI18n::gi()->{'Bepado_Productlist_Filter_aPreparedStatus__ERROR'} = 'Mal préparés';
MLI18n::gi()->{'Bepado_Productlist_Filter_aPreparedStatus__OPEN'} = 'Articles préparés non vérifiés';
MLI18n::gi()->{'Bepado_Productlist_Cell_aPreparedType__Chinese'} = 'Vente aux enchères';
MLI18n::gi()->{'Bepado_Productlist_Cell_aPreparedType__FixedPriceItem'} = 'Prix fixe';
MLI18n::gi()->{'Bepado_Productlist_Cell_aPreparedType__StoresFixedPrice'} = 'Prix fixe (boutique DaWanda)';
MLI18n::gi()->{'Bepado_Productlist_Header_sPreparedType'} = 'Format de la vente';
MLI18n::gi()->{'ML_BEPADO_TEXT_NO_MATCHED_PRODUCTS'} = 'Vous n\'avez encore aucun article préparé pour bepado. Avant de pouvoir télécharger vos articles, il vous faut les préparer. Pour cela, cliquez sur l\'onglet "préparer les articles".<br>
Là doivent être listé, les articles que vous voulez télécharger. S\'ils n\'apparaissent pas sous cet onglet, veuillez vérifier vos configurations et le statut de l\'article dans votre boutique (actif / inactif).';
