<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'fyndiq_prepare_form__legend__details'} = 'Product details';
MLI18n::gi()->{'fyndiq_prepare_form__legend__delivery'} = 'Delivery';
MLI18n::gi()->{'fyndiq_prepare_form__legend__categories'} = 'Category';
MLI18n::gi()->{'fyndiq_prepare_form__field__categories__label'} = 'Fyndiq categories';
MLI18n::gi()->{'fyndiq_prepare_form__field__primarycategory__label'} = '1. Marketplace category';
MLI18n::gi()->{'fyndiq_prepare_form__field__catattributes__label'} = 'Category attributes';
MLI18n::gi()->{'fyndiq_prepare_form__field__itemtitle__label'} = 'Title';
MLI18n::gi()->{'fyndiq_prepare_form__field__itemtitle__hint'} = 'Title max 64 Characters';
MLI18n::gi()->{'fyndiq_prepare_form__field__description__label'} = 'Description';
MLI18n::gi()->{'fyndiq_prepare_form__field__description__hint'} = 'Maximum of 4096 Characters. Some HTML-Tags and whose attributes are not allowed. Those count to the 4096 characters.';
MLI18n::gi()->{'fyndiq_prepare_form__field__brand__label'} = 'Brand';
MLI18n::gi()->{'fyndiq_prepare_form__field__images__label'} = 'Product pictures';
MLI18n::gi()->{'fyndiq_prepare_form__field__comparasionunit__label'} = 'Comparasion unit';
MLI18n::gi()->{'fyndiq_prepare_form__field__location__label'} = 'Location';
MLI18n::gi()->{'fyndiq_prepare_form__field__price__label'} = 'Price';
MLI18n::gi()->{'fyndiq_prepare_form__field__shippingtime__label'} = 'Delivery time';
MLI18n::gi()->{'fyndiq_prepare_form__field__shippingcost__label'} = 'Shipping costs';
MLI18n::gi()->{'fyndiq_prepareform_max_length_part1'} = 'Max length of';
MLI18n::gi()->{'fyndiq_prepareform_max_length_part2'} = 'attribute is';
MLI18n::gi()->{'fyndiq_prepare_form_category'} = 'Fyndiq categories are mandatory';
MLI18n::gi()->{'fyndiq_prepare_form_itemtitle'} = 'Title attribute is mandatory, and must be between 5 and 64 characters';
MLI18n::gi()->{'fyndiq_prepare_form_description'} = 'Description attribute is mandatory, and must be between 10 and 4096 characters';
MLI18n::gi()->{'fyndiq_prepareform_category_attribute'} = ' category attribute is mandatory.';
MLI18n::gi()->{'fyndiq_category_no_attributes'} = 'There are no attributes for this category.';
