<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'FYNDIQ_ML_LABEL_ARTICLE_SKU'} = 'SKU';
MLI18n::gi()->{'FYNDIQ_ML_LABEL_ARTICLE_NAME'} = 'Fyndiq Title';
MLI18n::gi()->{'FYNDIQ_ML_LABEL_ARTICLE_SHOP_PREIS'} = 'Shop price';
MLI18n::gi()->{'FYNDIQ_ML_LABEL_ARTICLE_MARKETPLACE_PREIS'} = 'Marketplace price';
MLI18n::gi()->{'fyndiq_inventory_listing_status'} = 'Status';
MLI18n::gi()->{'fyndiq_inventory_reject_message'} = 'Please contact the Fyndiq Support and ask for the reason why the product could not be listed.';
MLI18n::gi()->{'Fyndiq_Productlist_Cell_aPreparedStatus__OK__title'} = 'Prepared Status: Complete';
MLI18n::gi()->{'Fyndiq_Productlist_Cell_aPreparedStatus__ERROR__title'} = 'Faultly prepared';
MLI18n::gi()->{'Fyndiq_Productlist_Cell_aPreparedStatus__OPEN__title'} = 'Prepared not checked';
MLI18n::gi()->{'Fyndiq_Productlist_Filter_aPreparedStatus__OK'} = 'Prepared Status: Complete';
MLI18n::gi()->{'Fyndiq_Productlist_Filter_aPreparedStatus__ERROR'} = 'faultly prepared';
MLI18n::gi()->{'Fyndiq_Productlist_Filter_aPreparedStatus__OPEN'} = 'Prepared not checked';
