<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'sModuleNameFyndiq'} = 'Fyndiq';
MLI18n::gi()->{'ML_FYNDIQ_TEXT_NO_MATCHED_PRODUCTS'} = 'Vous n\'avez encore aucun article préparé pour Fyndig. Avant de pouvoir télécharger vos articles, il vous faut les préparer. Pour cela, cliquez sur l\'onglet "préparer les articles".<br>
Là doivent être listé, les articles que vous voulez télécharger. S\'ils n\'apparaissent pas sous cet onglet, veuillez vérifier vos configurations et le statut de l\'article dans votre boutique (actif / inactif).';
MLI18n::gi()->{'fyndiq_upload_explanation'} = 'Normalement les articles télécharges sur Fyndiq sont traité dans l\'espace d\'une heure. Ensuite les articles s\'afficherons dans votre compte Fyndiq.';
MLI18n::gi()->{'fyndiq_pre_upload_popup'} = 'Fyndiq limite actuellement le nombres d\'articles par téléchargement à 20.000. Voulez vous poursuivre le téléchargement ou annuler le téléchargement et sélectionner les articles à nouveau?';
