<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'sModuleNameEtsy'} = 'Etsy';
MLI18n::gi()->{'etsy_prepare_description_not_valid'} = 'Item description is too long. Maximum number of characters is 63000.';
MLI18n::gi()->{'etsy_prepare_images_not_valid'} = 'The picture is too big. The maximum allowed image size is 3000 x 3000 px.';
MLI18n::gi()->{'etsy_prepare_images_not_exist'} = 'There must be at least one image for the item !';
MLI18n::gi()->{'etsy_prepare_description_not_exist'} = 'Item description is too short.';
MLI18n::gi()->{'etsy_prepare_price_not_valid'} = 'Minimum item price on Etsy is 0.17£';
MLI18n::gi()->{'etsy_prepare_quantity_not_valid'} = 'The stock for a product must not be larger than 999.';

MLI18n::gi()->{'etsy_inventory_listing_status_new'} = 'Product will be created';
MLI18n::gi()->{'etsy_inventory_listing_status_active'} = 'Active';
MLI18n::gi()->{'etsy_inventory_listing_status_inactive'} = 'Inactive';
MLI18n::gi()->{'etsy_inventory_listing_status_expired'} = 'Expired';
MLI18n::gi()->{'etsy_inventory_listing_status_draft'} = 'Draft';
MLI18n::gi()->{'etsy_inventory_listing_status_sold_out'} = 'Sold Out';

MLI18n::gi()->{'etsy_checkin_purge_popup_text'} = '
<p><strong>Please note:</strong> You are about to completely replace your inventory on Etsy. This process first completely deletes your marketplace inventory and then replaces it with the items selected here.</p>
<p>Etsy charges fees for creating new listings. Contact the Etsy support if you have any questions about your Etsy plan.</p>
<p>Do you really want to proceed?</p>
';
MLI18n::gi()->{'etsy_checkin_popup_text'} = '<p><strong>Please note:</strong> Etsy charges fees for creating new listings. Contact the Etsy support if you have any questions about your Etsy plan.</p>';
