<?php
/**
 * 888888ba                 dP  .88888.                    dP
 * 88    `8b                88 d8'   `88                   88
 * 88aaaa8P' .d8888b. .d888b88 88        .d8888b. .d8888b. 88  .dP  .d8888b.
 * 88   `8b. 88ooood8 88'  `88 88   YP88 88ooood8 88'  `"" 88888"   88'  `88
 * 88     88 88.  ... 88.  .88 Y8.   .88 88.  ... 88.  ... 88  `8b. 88.  .88
 * dP     dP `88888P' `88888P8  `88888'  `88888P' `88888P' dP   `YP `88888P'
 *
 *                          m a g n a l i s t e r
 *                                      boost your Online-Shop
 *
 * -----------------------------------------------------------------------------
 * (c) 2010 - 2019 RedGecko GmbH -- http://www.redgecko.de
 *     Released under the MIT License (Expat)
 * -----------------------------------------------------------------------------
 */

/* Autogenerated file. Do not change! */

MLI18n::gi()->{'googleshopping_prepare_form__legend__details'} = 'Fiche Produit';
MLI18n::gi()->{'googleshopping_prepare_form__legend__categories'} = 'Catégorie DaWanda';
MLI18n::gi()->{'googleshopping_prepare_form__legend__attributes'} = 'attributs';
MLI18n::gi()->{'googleshopping_prepare_form__field__producttype__label'} = 'Type de produit';
MLI18n::gi()->{'googleshopping_prepare_form__field__producttype__hint'} = '';
MLI18n::gi()->{'googleshopping_prepare_form__field__listingduration__label'} = 'Durée de validité ';
MLI18n::gi()->{'googleshopping_prepare_form__field__listingduration__hint'} = '';
MLI18n::gi()->{'googleshopping_prepare_form__field__returnpolicy__label'} = 'Droit de révocation';
MLI18n::gi()->{'googleshopping_prepare_form__field__returnpolicy__hint'} = '';
MLI18n::gi()->{'googleshopping_prepare_form__field__shippingservice__label'} = 'Profil d\'expédition';
MLI18n::gi()->{'googleshopping_prepare_form__field__shippingservice__hint'} = '';
MLI18n::gi()->{'googleshopping_prepare_form__field__mpcolors__label'} = 'Couleurs du produit';
MLI18n::gi()->{'googleshopping_prepare_form__field__mpcolors__hint'} = '';
MLI18n::gi()->{'googleshopping_prepare_form__field__mpcolors__subfieldlabel'} = 'Couleur du produit';
MLI18n::gi()->{'googleshopping_prepare_form__field__mpcolors__valuenocolor'} = 'Pas de couleur';
MLI18n::gi()->{'googleshopping_prepare_form__field__categories__label'} = 'Catégorie DaWanda';
MLI18n::gi()->{'googleshopping_prepare_form__field__categories__hint'} = '';
MLI18n::gi()->{'googleshopping_prepare_form__field__primarycategory__label'} = 'Catégorie Place de marché';
MLI18n::gi()->{'googleshopping_prepare_form__field__primarycategory__hint'} = '';
MLI18n::gi()->{'googleshopping_prepare_form__field__secondarycategory__label'} = '2. Catégorie Place de marché:';
MLI18n::gi()->{'googleshopping_prepare_form__field__secondarycategory__hint'} = '';
MLI18n::gi()->{'googleshopping_prepare_form__field__storecategory__label'} = 'Catégorie en boutique:';
MLI18n::gi()->{'googleshopping_prepare_form__field__storecategory__hint'} = '';
MLI18n::gi()->{'googleshopping_prepare_form__field__attributes__label'} = 'Attributs';
MLI18n::gi()->{'googleshopping_prepare_form__field__attributes__hint'} = '';
MLI18n::gi()->{'prepareform_listingduration_values__-1'} = 'Récupération des données automatique après 120 jours';
MLI18n::gi()->{'prepareform_listingduration_values__120'} = 'Pas de récupération automatique des données';
MLI18n::gi()->{'googleshopping_varmatch_attribute_deleted_from_mp'} = '{#i18n:attributes_matching_attribute_deleted_from_marketplace_message#}';
MLI18n::gi()->{'googleshopping_prepare_variations_manualy_matched'} = ' - Manualy matched';
MLI18n::gi()->{'googleshopping_prepare_variations_already_matched'} = '   Already matched';
MLI18n::gi()->{'googleshopping_prepare_variations_choose_mp_value'} = 'Choose value from marketplace';