<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'tradoria_prepare_form__legend__details'} = 'Fiche Produit';
MLI18n::gi()->{'tradoria_prepare_form__legend__categories'} = 'Catégories Rakuten';
MLI18n::gi()->{'tradoria_prepare_form__field__categories__label'} = 'Catégories Rakuten';
MLI18n::gi()->{'tradoria_prepare_form__field__categories__hint'} = '';
MLI18n::gi()->{'tradoria_prepare_form__field__primarycategory__label'} = '1. Catégorie de la place de marché';
MLI18n::gi()->{'tradoria_prepare_form__field__primarycategory__hint'} = '';
MLI18n::gi()->{'tradoria_prepare_variations_title'} = '{#i18n:attributes_matching_tab_title#}';
MLI18n::gi()->{'tradoria_prepare_apply_form__legend__shipping'} = 'Shipping';
MLI18n::gi()->{'tradoria_prepare_apply_form__field__shippingtime__label'} = 'Processing time in days';
MLI18n::gi()->{'tradoria_prepare_apply_form__field__shippingtime__help'} = 'Specifies the time period (in days) between the order receipt for an item and the shipping of the item. If you do not specify a value here, the default delivery time is 1-2 business days. Use this field if the delivery time for an item is more than two business days.';
MLI18n::gi()->{'tradoria_prepare_apply_form__field__shippingtime__values__0'} = 'Immediately available (delivery time 1-4 working days)';
MLI18n::gi()->{'tradoria_prepare_apply_form__field__shippingtime__values__3'} = 'ready for shipment in 3 working days (delivery time 4-6 working days)';
MLI18n::gi()->{'tradoria_prepare_apply_form__field__shippingtime__values__5'} = 'ready for shipment in 5 working days (delivery time 6-8 working days)';
MLI18n::gi()->{'tradoria_prepare_apply_form__field__shippingtime__values__7'} = 'ready for shipment in 7 working days (delivery time 8-10 working days)';
MLI18n::gi()->{'tradoria_prepare_apply_form__field__shippingtime__values__10'} = 'ready for shipment in 10 working days (delivery time 10-15 working days)';
MLI18n::gi()->{'tradoria_prepare_apply_form__field__shippingtime__values__15'} = 'ready for shipment in 15 working days (delivery time 15-20 working days)';
MLI18n::gi()->{'tradoria_prepare_apply_form__field__shippingtime__values__20'} = 'ready for shipment in 20 working days (delivery time 20-30 working days)';
MLI18n::gi()->{'tradoria_prepare_apply_form__field__shippingtime__values__30'} = 'ready for shipment in 30 working days (delivery time 30-40 working days)';
MLI18n::gi()->{'tradoria_prepare_apply_form__field__shippingtime__values__40'} = 'ready for shipment in 40 working days (delivery time 40-50 working days)';
MLI18n::gi()->{'tradoria_prepare_apply_form__field__shippingtime__values__50'} = 'ready for shipment in 50 working days (delivery time 50-60 working days)';
MLI18n::gi()->{'tradoria_prepare_apply_form__field__shippingtime__values__60'} = 'Delivery time longer than 3 months';
MLI18n::gi()->{'tradoria_prepare_apply_form__field__shippingtime__optional__checkbox__labelNegativ'} = 'Use always processing time from web-shop';

