<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'sModuleNameTradoria'} = 'Rakuten';
MLI18n::gi()->{'ML_TRADORIA_CATEGORY_MATCHING'} = 'Category Matching';
MLI18n::gi()->{'tradoria_upload_explanation'} = 'Uploaded items are usually placed within one hour on Rakuten. After that, you can see items on your Rakuten management page.';

