<?php
/*
 * 888888ba                 dP  .88888.                    dP
 * 88    `8b                88 d8'   `88                   88
 * 88aaaa8P' .d8888b. .d888b88 88        .d8888b. .d8888b. 88  .dP  .d8888b.
 * 88   `8b. 88ooood8 88'  `88 88   YP88 88ooood8 88'  `"" 88888"   88'  `88
 * 88     88 88.  ... 88.  .88 Y8.   .88 88.  ... 88.  ... 88  `8b. 88.  .88
 * dP     dP `88888P' `88888P8  `88888'  `88888P' `88888P' dP   `YP `88888P'
 *
 *                          m a g n a l i s t e r
 *                                      boost your Online-Shop
 *
 * -----------------------------------------------------------------------------
 * (c) 2010 - 2020 RedGecko GmbH -- http://www.redgecko.de
 *     Released under the MIT License (Expat)
 * -----------------------------------------------------------------------------
 */

/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Shopware_Marketplace_Configuration_PaymentMethod_Info'} = '<p> Mode de paiement qui sera attribué à toutes les commandes effectuées sur {#platformName#} lors de l\'importation des commandes. <br>
Valeur par défaut : "Attribution automatique"</p>
<p>
Si l\'"Attribution automatique" est sélectionnée magnalister reprend le mode de paiement que le client a choisit lors de sa commande sur {#platformName#}.
Le mode de paiement sera alors ajouté à votre boutique dans "Shopware" > "Paramètres" > "Moyens de paiement". </p>
<p>Vous pouvez définir d\'autres modes de paiements qui s\'afficheront dans le menu déroulant en vous rendant sur "Shopware" > "moyens de paiement".</p>
<p>Ce réglage est important pour l\'impression des bons de livraison et des factures, mais aussi pour le traitement ultérieur des commandes dans votre boutique ainsi que dans votre gestion des marchandises.</p>
';
MLI18n::gi()->{'Shopware_EBay_Configuration_ShippingMethod_Info'} = '<p> Mode de livraison qui sera attribué à toutes les commandes effectuées sur {#platformName#} lors de l\'importation des commandes. <br>
Valeur par défaut : "Attribution automatique"</p>
<p>
Si l\'"Attribution automatique" est sélectionnée magnalister reprend le mode de livraison que le client a choisit lors de sa commande sur {#platformName#}.
Le mode de livraison sera alors ajouté à votre boutique dans "Shopware" > "Paramètres" > "Frais de port". </p>
<p>Vous pouvez définir d\'autres modes de livraison qui s\'afficheront dans le menu déroulant en vous rendant sur "Shopware" > "frais de port".</p>
<p>Ce réglage est important pour l\'impression des bons de livraison et des factures, mais aussi pour le traitement ultérieur des commandes dans votre boutique ainsi que dans votre gestion des marchandises.</p>
';
MLI18n::gi()->{'Shopware_Amazon_Configuration_ShippingMethod_Info'} = '<b>Mode d’envoi des commandes</b><br />
<br />
Choisissez ici le mode d’envoi qui sera associé uniformément à toutes les commandes.<br />
<br />
Voici les différentes options qui s’offrent à vous :<br />
<ol>
<li><b>Modes d’envoi pris en charge par la place de marché</b><br />
<br />
Choisissez un mode d’envoi dans la liste du menu déroulant. Seules les options prises en charge par la place de marché s’affichent.<br />
<br />
</li>
<li><b>Modes d’envoi sur le gestionnaire des champs libres de la boutique en ligne</b><br />
<br />
Choisissez un mode d’envoi à partir d’un champ libre de la boutique en ligne. <br />
<br />
</li>
<li><b>Sélection automatique</b><br />
<br />
Pour chaque pays de destination, magnalister sélectionne automatiquement le mode d’envoi placé en tête de liste dans le module de calcul des frais de port pour la boutique en ligne concernée. 
</li>
</ol>';
MLI18n::gi()->{'Shopware_Ebay_Configuration_Updateable_OrderStatus_Label'} = 'Permettre le changement de statut de commande si';
MLI18n::gi()->{'Shopware_Ebay_Configuration_Updateable_PaymentStatus_Label'} = 'Permettre le changement de statut de commande si';
MLI18n::gi()->{'Shopware_Ebay_Configuration_Updateable_PaymentStatus_Info'} = 'Vous pouvez avec cette fonction synchroniser le changement de statut des commandes après paiements sur eBay. <br>
Normalement, les changements de statut de commande n\'ont pas d’incidence sur le statut de paiement sur eBay. <br>
<br>
Si vous ne souhaitez aucun changement de statuts au paiement de la commande, désactivez la case à droite de la fenêtre de choix.<br>
<br>
<strong>Remarque :</strong> Le statut des commandes combinées ne sera modifié, que si toutes les parties ont été payées.';
MLI18n::gi()->{'Shopware_Ebay_Configuration_ArticleDescriptionTemplate_sExternalDesc'} = 'Liste des champs de texte libre disponibles pour la description de l’article : <br>
<br>
#TITLE#<br>
<BLOCKQUOTE>
<p>nom du produit</p>
</BLOCKQUOTE>
#ARTNR#
<BLOCKQUOTE>
<p>numéro d’article dans votre boutique</p>
</BLOCKQUOTE>
#PID#
<BLOCKQUOTE>
<p>identifiant du produit dans votre boutique</p>
</BLOCKQUOTE>
#SHORTDESCRIPTION#
<BLOCKQUOTE>
<p>description abrégée de l’article de votre boutique</p>
</BLOCKQUOTE>
#DESCRIPTION#
	<BLOCKQUOTE>
<p>description de l’article de votre boutique</p>
	</BLOCKQUOTE>
#PICTURE1#
	<BLOCKQUOTE>
<p>première image de l’article</p>
	</BLOCKQUOTE>
#PICTURE2# etc.
<BLOCKQUOTE>
<p>deuxième image de l’article; vous pouvez ajouter plus d’images de l’article (autant que dans votre boutique) en saisissant #PICTURE3#, #PICTURE4# etc.</p>
</BLOCKQUOTE>
<br>
<p><font color="red">(les paramètres suivants ne sont pas disponibles sur PrestaShop)</font></p>
<br>
<br>

Champs de texte libre pour description d’article :<br>
<br>
#Description1# #Freetextfield1#<br>
#Description2# #Freetextfield2#<br>
#description12# #freetextfield1#<br>
<br>
Prise en charge des champs de texte libre: le chiffre derrière le paramètre générique correspond à la position du texte.<br>
<br>
#PROPERTIES#<br>
liste contenant toutes les caractéristiques du produit. Vous pouvez changer l’apparence de la liste avec CSS.
';
MLI18n::gi()->{'Shopware_Ebay_Configuration_ArticleDescriptionTemplate_sDefault'} = '<style>
ul.magna_properties_list {
    margin: 0 0 20px 0;
    list-style: none;
    padding: 0;
    display: inline-block;
    width: 100%
}
ul.magna_properties_list li {
    border-bottom: none;
    width: 100%;
    height: 20px;
    padding: 6px 5px;
    float: left;
    list-style: none;
}
ul.magna_properties_list li.odd {
    background-color: rgba(0, 0, 0, 0.05);
}
ul.magna_properties_list li span.magna_property_name {
    display: block;
    float: left;
    margin-right: 10px;
    font-weight: bold;
    color: #000;
    line-height: 20px;
    text-align: left;
    font-size: 12px;
    width: 50%;
}
ul.magna_properties_list li span.magna_property_value {
    color: #666;
    line-height: 20px;
    text-align: left;
    font-size: 12px;

    width: 50%;
}
</style>
<p>#TITLE#</p>
<p>#ARTNR#</p>
<p>#SHORTDESCRIPTION#</p>
<p>#PICTURE1#</p>
<p>#PICTURE2#</p>
<p>#PICTURE3#</p>
<p>#DESCRIPTION#</p>
<p>#MOBILEDESCRIPTION#</p>
<p>#Description1# #Freetextfield1#</p>
<p>#Description2# #Freetextfield2#</p>
<div>#PROPERTIES#</div>';
MLI18n::gi()->{'Shopware_Ebay_Configuration_PaidStatus_Payment_sLabel'} = 'Statut de paiement';
MLI18n::gi()->{'Shopware_Ebay_Configuration_PaidStatus_Order_sLabel'} = 'Statut des commandes';
MLI18n::gi()->{'Shopware_Amazon_Configuration_PaymentStatus_sLabel'} = 'Statut de paiement dans la boutique';
MLI18n::gi()->{'Shopware_Amazon_Configuration_PaymentStatus_sDescription'} = 'Le statut de paiement dans la boutique en ligne, a récemment reçu une nouvelle commande qui devrait arriver automatiquement dans la boutique.';
MLI18n::gi()->{'form_config_orderimport_exchangerate_update_help'} = 'Si la devise utilisé dans votre boutique en ligne est différente de celle de la place de marché, magnalister calcule le taux de change par rapport au taux que vous avez défini dans votre boutique en ligne. <br>
<br>
En activant cette fonction, le taux de change actuel défini par "alphavantage" sera appliqué à vos articles. Les prix dans votre boutique en ligne seront également mis à jour.<br>
<br>
L’activation et la désactivation de cette fonction prend effet toutes les heures.<br>
<br>
Les fonctions suivantes provoqueront une actualisation du taut de change :
<ul>
<li>Importation des commandes</li>
<li>Préparer les articles</li>
<li>Charger les articles</li>
<li>Synchronisation des prix et des stocks</li>
</ul>
<b>Avertissement :</b> RedGecko GmbH n\'assume aucune responsabilité quand à l\'exactitude du taux de change. Veuillez vérifier en contrôlant les prix de vos articles sur la place de marché.            ';
MLI18n::gi()->{'form_config_orderimport_exchangerate_update_alert'} = '<b>Attention!</b> <br>
En activant cette fonction, le taux de change actuel défini par "alphavantage" sera appliqué à vos articles. Les prix dans votre boutique en ligne seront également mis à jour.<br>
<br>
les fonctions suivantes provoquent une mise à jour des prix:
<ul>
<li>Importation des commandes</li>
<li>Préparer les articles</li>
<li>Charger les articles</li>
<li>Synchroniser les prix et les stocks</li>
<br>
<b>Avertissement :</b> RedGecko GmbH n\'assume aucune responsabilité pour l\'exactitude du taux de change. Veuillez vérifier en contrôlant les prix de vos articles sur la place de marché.';
MLI18n::gi()->{'global_config_price_field_price.discountmode_label'} = 'Mode de rabais';
MLI18n::gi()->{'orderimport_vatcustomergroup_label'} = 'Appliquer les règles fiscales de la boutique en ligne pour les commandes du groupe de clients';
MLI18n::gi()->{'orderimport_vatcustomergroup_help'} = '
<p>
Par défaut, magnalister utilise pour le calcul de la taxe d\'importation des commandes, les règles de taxation de la boutique en ligne pour le groupe de clients que vous avez sélectionné dans la configuration "Groupe de clients".
</p>
<p>
Avec l\'option "Appliquer les règles fiscales de la boutique en ligne pour les commandes du groupe de clients", vous pouvez choisir un groupe de clients différent pour le calcul de la taxe.
</p>
<p>
Les règles fiscales de la boutique en ligne se trouvent dans votre boutique sous la rubrique :<br>
Paramètres de base -> Paramètres de la boutique -> Taxes.
</p>
' ;
