<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'sAddAewShopAttributeInstruction'} = '<strong>Important:  </strong><br /><br />
Data can only be saved if you additionally match the following parameters to your shop attributes in magnalister > global configuration > product attributes. You can administrate those in magento under catalogue > attributes.
<ul>
        <li>Manufacturer model number (MPN) </li>
	<li>EAN</li>
    <li>Manufacturer *¹</li>
        </ul><br />
*¹ <font color="green" >The manufacturer can be configurated differing additionally under “magnalister” > “hood” > “configuration” > “item preparation” > “brand”.</font>        ';
