<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'sModuleNameEtsy'} = 'Etsy';
MLI18n::gi()->{'etsy_prepare_description_not_valid'} = 'Die Artikelbeschreibung ist zu lang. Die maximale Anzahl der Zeichen beträgt 63000.';
MLI18n::gi()->{'etsy_prepare_images_not_valid'} = 'Das Bild ist zu groß. Die maximal zulässige Bildgröße beträgt 3000 x 3000 px.';
MLI18n::gi()->{'etsy_prepare_images_not_exist'} = 'Es muss mindestens ein Bild für den Artikel vorhanden sein!';
MLI18n::gi()->{'etsy_prepare_description_not_exist'} = 'Die Artikelbeschreibung ist zu kurz.';
MLI18n::gi()->{'etsy_prepare_price_not_valid'} = 'Minimaler Artikelpreis auf Etsy ist 0.17£.';
MLI18n::gi()->{'etsy_prepare_quantity_not_valid'} = 'Der Bestand für ein Produkt darf nicht größe als 999 sein.';

MLI18n::gi()->{'etsy_inventory_listing_status_new'} = 'Produkt wird erstellt';
MLI18n::gi()->{'etsy_inventory_listing_status_active'} = 'Aktiv';
MLI18n::gi()->{'etsy_inventory_listing_status_inactive'} = 'Inaktiv';
MLI18n::gi()->{'etsy_inventory_listing_status_expired'} = 'Expired';
MLI18n::gi()->{'etsy_inventory_listing_status_draft'} = 'Draft';
MLI18n::gi()->{'etsy_inventory_listing_status_sold_out'} = 'Sold Out';

MLI18n::gi()->{'etsy_checkin_purge_popup_text'} = '
<p><strong>Hinweis:</strong> Sie sind dabei Ihr Inventar auf Etsy vollst&auml;ndig zu ersetzen. Dieser Vorgang l&ouml;scht erst komplett Ihren Marktplatz-Bestand und ersetzt ihn dann mit den hier ausgew&auml;hlten Artikeln.</p>
<p>Etsy berechnet Einstellgeb&uuml;hren f&uuml;r das Erstellen neuer Angebote. F&uuml;r mehr Informationen pr&uuml;fen Sie bitte Ihren Etsy H&auml;ndler-Tarif.</p>
<p>Wollen Sie wirklich fortfahren?</p>
';
MLI18n::gi()->{'etsy_checkin_popup_text'} = '<p><strong>Bitte beachten Sie:</strong> Etsy berechnet Einstellgeb&uuml;hren f&uuml;r das Erstellen neuer Angebote. F&uuml;r mehr Informationen pr&uuml;fen Sie bitte Ihren Etsy H&auml;ndler-Tarif.</p>';
