<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'mercadolivre_prepare_form__legend__details'} = 'product details';
MLI18n::gi()->{'mercadolivre_prepare_form__legend__categories'} = 'MercadoLivre categories';
MLI18n::gi()->{'mercadolivre_prepare_form__legend__variationmatching__0'} = '{#i18n:attributes_matching_required_attributes#}';
MLI18n::gi()->{'mercadolivre_prepare_form__legend__variationmatching__1'} = '{#i18n:attributes_matching_title#}';
MLI18n::gi()->{'mercadolivre_prepare_form__legend__variationmatchingoptional__0'} = '{#i18n:attributes_matching_optional_attributes#}';
MLI18n::gi()->{'mercadolivre_prepare_form__legend__variationmatchingoptional__1'} = '{#i18n:attributes_matching_title#}';
MLI18n::gi()->{'mercadolivre_prepare_form__legend__variationmatchingcustom__0'} = '{#i18n:attributes_matching_custom_attributes#}';
MLI18n::gi()->{'mercadolivre_prepare_form__legend__variationmatchingcustom__1'} = '{#i18n:attributes_matching_title#}';
MLI18n::gi()->{'mercadolivre_prepare_form__legend__configmatching'} = 'MercadoLivre Config';
MLI18n::gi()->{'mercadolivre_prepare_form__field__categories__label'} = 'MercadoLivre Categories';
MLI18n::gi()->{'mercadolivre_prepare_form__field__primarycategory__label'} = '1. Marketplace category';
MLI18n::gi()->{'mercadolivre_prepare_form__field__currency__label'} = 'Currency';
MLI18n::gi()->{'mercadolivre_prepare_form__field__itemcondition__label'} = 'Item condition';
MLI18n::gi()->{'mercadolivre_prepare_form__field__listingtype__label'} = 'Listing type';
MLI18n::gi()->{'mercadolivre_prepare_form__field__buyingmode__label'} = 'Buying mode';
MLI18n::gi()->{'mercadolivre_prepare_form__field__shippingmode__label'} = 'Shipping mode';
MLI18n::gi()->{'mercadolivre_prepare_form__field__webshopattribute__label'} = 'Web Shop Attribute';
MLI18n::gi()->{'mercadolivre_prepare_form__field__attributematching__matching__titlesrc'} = 'Shop Value';
MLI18n::gi()->{'mercadolivre_prepare_form__field__attributematching__matching__titledst'} = 'MercadoLivre Value';
MLI18n::gi()->{'mercadolivre_prepareform_max_length_part1'} = 'Max length of';
MLI18n::gi()->{'mercadolivre_prepareform_max_length_part2'} = 'attribute is';
MLI18n::gi()->{'mercadolivre_prepareform_reqired_fieds'} = '<p><b>Hint:</b>  Fields marked with <span class="bull">•</span> are mandantory and must be filled.</p>';
