<?php
/*
 * 888888ba                 dP  .88888.                    dP
 * 88    `8b                88 d8'   `88                   88
 * 88aaaa8P' .d8888b. .d888b88 88        .d8888b. .d8888b. 88  .dP  .d8888b.
 * 88   `8b. 88ooood8 88'  `88 88   YP88 88ooood8 88'  `"" 88888"   88'  `88
 * 88     88 88.  ... 88.  .88 Y8.   .88 88.  ... 88.  ... 88  `8b. 88.  .88
 * dP     dP `88888P' `88888P8  `88888'  `88888P' `88888P' dP   `YP `88888P'
 *
 *                          m a g n a l i s t e r
 *                                      boost your Online-Shop
 *
 * -----------------------------------------------------------------------------
 * (c) 2010 - 2022 RedGecko GmbH -- http://www.redgecko.de
 *     Released under the MIT License (Expat)
 * -----------------------------------------------------------------------------
 */

/* Autogenerated file. Do not change! */

MLI18n::gi()->{'form_config_orderimport_shop_lable'} = 'Boutique à exploiter';
MLI18n::gi()->{'form_config_orderimport_shop_help'} = 'Si vous gérez une multiboutique, veuillez sélectionner la boutique que vous souhaitez connecter aux places de marché.';
MLI18n::gi()->{'form_config_orderimport_imagesize_lable'} = 'Taille d\'image';
MLI18n::gi()->{'form_config_orderimport_imagesize_help'} = 'Donnez ici la largeur en pixel, que votre image doit avoir sur votre page. La hauteur sera automatiquement ajustée. <br>
Vos images originales se trouvent dans le dossier image sous l’adresse : <i>shop-root/media/image</i>. Après ajustage,  elles sont versées dans le dossier : <i>shop-root/media/image/magnalister</i>, et sont prêtes à être utilisées par les places de marché.';
MLI18n::gi()->{'form_config_orderimport_imagesize_hint'} = 'Enregistrée sous l\'onglet: {#setting:sImagePath#}';
MLI18n::gi()->{'form_config_send_mailcontentcontailner_testmail'} = 'Aperçu';

MLI18n::gi()->form_orderimport_paymentandshipping_values_textfield_title = 'Champs de texte';MLI18n::gi()->{'form_config_send_mailcontentcontailner_testmail'} = 'Aperçu';
MLI18n::gi()->{'form_config_orderimport_shop_lable'} = 'Boutique à exploiter';
MLI18n::gi()->{'form_config_orderimport_imagesize_hint'} = 'Enregistrée sous l&apos;onglet: {#setting:sImagePath#}';
MLI18n::gi()->{'form_config_orderimport_imagesize_lable'} = 'Taille d&apos;image';
MLI18n::gi()->{'form_orderimport_paymentandshipping_values_textfield_title'} = 'Champs de texte';
MLI18n::gi()->{'form_config_orderimport_shop_help'} = 'Si vous gérez une multiboutique, veuillez sélectionner la boutique que vous souhaitez connecter aux places de marché.';
MLI18n::gi()->{'form_config_orderimport_imagesize_help'} = 'Donnez ici la largeur en pixel, que votre image doit avoir sur votre page. La hauteur sera automatiquement ajustée. <br>
Vos images originales se trouvent dans le dossier image sous l’adresse : <i>shop-root/media/image</i>. Après ajustage,  elles sont versées dans le dossier : <i>shop-root/media/image/magnalister</i>, et sont prêtes à être utilisées par les places de marché.';
