<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'dummymodule_config_general_mwstoken_help'} = 'dummymodule_config_general_mwstoken_help';
MLI18n::gi()->{'dummymodule_config_general_autosync'} = 'dummymodule_config_general_autosync';
MLI18n::gi()->{'dummymodule_config_general_nosync'} = 'dummymodule_config_general_nosync';
MLI18n::gi()->{'dummymodule_config_account_title'} = 'dummymodule_config_account_title';
MLI18n::gi()->{'dummymodule_config_account_prepare'} = 'dummymodule_config_account_prepare';
MLI18n::gi()->{'dummymodule_config_account_price'} = 'dummymodule_config_account_price';
MLI18n::gi()->{'dummymodule_configform_orderstatus_sync_values__auto'} = '{#i18n:dummymodule_config_general_autosync#}';
MLI18n::gi()->{'dummymodule_configform_orderstatus_sync_values__trigger'} = 'dummymodule_configform_orderstatus_sync_values__trigger';
MLI18n::gi()->{'dummymodule_configform_orderstatus_sync_values__no'} = '{#i18n:dummymodule_config_general_nosync#}';
MLI18n::gi()->{'dummymodule_configform_sync_values__auto'} = '{#i18n:dummymodule_config_general_autosync#}';
MLI18n::gi()->{'dummymodule_configform_sync_values__no'} = '{#i18n:dummymodule_config_general_nosync#}';
MLI18n::gi()->{'dummymodule_configform_stocksync_values__rel'} = 'dummymodule_configform_stocksync_values__rel';
MLI18n::gi()->{'dummymodule_configform_stocksync_values__fba'} = 'dummymodule_configform_stocksync_values__fba';
MLI18n::gi()->{'dummymodule_configform_stocksync_values__no'} = '{#i18n:dummymodule_config_general_nosync#}';
MLI18n::gi()->{'dummymodule_configform_pricesync_values__auto'} = '{#i18n:dummymodule_config_general_autosync#}';
MLI18n::gi()->{'dummymodule_configform_pricesync_values__edit'} = 'Editar artigo define preço na Amazon igual ao preço da loja';
MLI18n::gi()->{'dummymodule_configform_pricesync_values__no'} = '{#i18n:dummymodule_config_general_nosync#}';
MLI18n::gi()->{'dummymodule_configform_orderimport_payment_values__textfield__title'} = 'dummymodule_configform_orderimport_payment_values__textfield__title';
MLI18n::gi()->{'dummymodule_configform_orderimport_payment_values__textfield__textoption'} = 'dummymodule_configform_orderimport_payment_values__textfield__textoption';
MLI18n::gi()->{'dummymodule_configform_orderimport_payment_values__Amazon__title'} = 'dummymodule_configform_orderimport_payment_values__Amazon__title';
MLI18n::gi()->{'dummymodule_configform_orderimport_shipping_values__textfield__title'} = 'dummymodule_configform_orderimport_shipping_values__textfield__title';
MLI18n::gi()->{'dummymodule_configform_orderimport_shipping_values__textfield__textoption'} = 'dummymodule_configform_orderimport_shipping_values__textfield__textoption';
MLI18n::gi()->{'dummymodule_config_account_sync'} = 'dummymodule_config_account_sync';
MLI18n::gi()->{'dummymodule_config_account_orderimport'} = 'dummymodule_config_account_orderimport';
MLI18n::gi()->{'dummymodule_config_account_emailtemplate'} = 'dummymodule_config_account_emailtemplate';
MLI18n::gi()->{'dummymodule_config_account_emailtemplate_sender'} = 'dummymodule_config_account_emailtemplate_sender';
MLI18n::gi()->{'dummymodule_config_account_emailtemplate_sender_email'} = 'dummymodule_config_account_emailtemplate_sender_email';
MLI18n::gi()->{'dummymodule_config_account_emailtemplate_subject'} = 'dummymodule_config_account_emailtemplate_subject';
MLI18n::gi()->{'dummymodule_config_account_emailtemplate_content'} = 'dummymodule_config_account_emailtemplate_content';
MLI18n::gi()->{'dummymodule_config_account__legend__account'} = 'dummymodule_config_account__legend__account';
MLI18n::gi()->{'dummymodule_config_account__legend__tabident'} = '';
MLI18n::gi()->{'dummymodule_config_account__field__tabident__label'} = '{#i18n:ML_LABEL_TAB_IDENT#}';
MLI18n::gi()->{'dummymodule_config_account__field__tabident__help'} = '{#i18n:ML_TEXT_TAB_IDENT#}';
MLI18n::gi()->{'dummymodule_config_account__field__username__label'} = 'dummymodule_config_account__field__username__label';
MLI18n::gi()->{'dummymodule_config_account__field__username__hint'} = '';
MLI18n::gi()->{'dummymodule_config_account__field__password__label'} = 'dummymodule_config_account__field__password__label';
MLI18n::gi()->{'dummymodule_config_account__field__password__help'} = 'dummymodule_config_account__field__password__help';
MLI18n::gi()->{'dummymodule_config_account__field__mwstoken__label'} = 'dummymodule_config_account__field__mwstoken__label';
MLI18n::gi()->{'dummymodule_config_account__field__mwstoken__help'} = '{#i18n:dummymodule_config_general_mwstoken_help#}';
MLI18n::gi()->{'dummymodule_config_account__field__merchantid__label'} = 'dummymodule_config_account__field__merchantid__label';
MLI18n::gi()->{'dummymodule_config_account__field__merchantid__help'} = '{#i18n:dummymodule_config_general_mwstoken_help#}';
MLI18n::gi()->{'dummymodule_config_account__field__marketplaceid__label'} = 'dummymodule_config_account__field__marketplaceid__label';
MLI18n::gi()->{'dummymodule_config_account__field__marketplaceid__help'} = '{#i18n:dummymodule_config_general_mwstoken_help#}';
MLI18n::gi()->{'dummymodule_config_account__field__site__label'} = 'dummymodule_config_account__field__site__label';
MLI18n::gi()->{'dummymodule_config_prepare__legend__prepare'} = 'dummymodule_config_prepare__legend__prepare';
MLI18n::gi()->{'dummymodule_config_prepare__legend__matchingvalues'} = 'dummymodule_config_prepare__legend__matchingvalues';
MLI18n::gi()->{'dummymodule_config_prepare__legend__machingbehavior'} = 'dummymodule_config_prepare__legend__machingbehavior';
MLI18n::gi()->{'dummymodule_config_prepare__legend__apply'} = 'dummymodule_config_prepare__legend__apply';
MLI18n::gi()->{'dummymodule_config_prepare__legend__shipping'} = 'dummymodule_config_prepare__legend__shipping';
MLI18n::gi()->{'dummymodule_config_prepare__legend__upload'} = 'dummymodule_config_prepare__legend__upload';
MLI18n::gi()->{'dummymodule_config_prepare__field__prepare.status__label'} = 'dummymodule_config_prepare__field__prepare.status__label';
MLI18n::gi()->{'dummymodule_config_prepare__field__prepare.status__valuehint'} = 'dummymodule_config_prepare__field__prepare.status__valuehint';
MLI18n::gi()->{'dummymodule_config_prepare__field__topten__label'} = 'dummymodule_config_prepare__field__topten__label';
MLI18n::gi()->{'dummymodule_config_prepare__field__topten__help'} = 'dummymodule_config_prepare__field__topten__help';
MLI18n::gi()->{'dummymodule_config_prepare__field__checkin.status__label'} = 'dummymodule_config_prepare__field__checkin.status__label';
MLI18n::gi()->{'dummymodule_config_prepare__field__checkin.status__valuehint'} = 'dummymodule_config_prepare__field__checkin.status__valuehint';
MLI18n::gi()->{'dummymodule_config_prepare__field__lang__label'} = 'dummymodule_config_prepare__field__lang__label';
MLI18n::gi()->{'dummymodule_config_prepare__field__itemcondition__label'} = 'dummymodule_config_prepare__field__itemcondition__label';
MLI18n::gi()->{'dummymodule_config_prepare__field__internationalshipping__label'} = 'dummymodule_config_prepare__field__internationalshipping__label';
MLI18n::gi()->{'dummymodule_config_prepare__field__multimatching__label'} = 'dummymodule_config_prepare__field__multimatching__label';
MLI18n::gi()->{'dummymodule_config_prepare__field__multimatching__valuehint'} = 'dummymodule_config_prepare__field__multimatching__valuehint';
MLI18n::gi()->{'dummymodule_config_prepare__field__multimatching__help'} = 'dummymodule_config_prepare__field__multimatching__help';
MLI18n::gi()->{'dummymodule_config_prepare__field__multimatching.itemsperpage__label'} = 'dummymodule_config_prepare__field__multimatching.itemsperpage__label';
MLI18n::gi()->{'dummymodule_config_prepare__field__multimatching.itemsperpage__help'} = 'dummymodule_config_prepare__field__multimatching.itemsperpage__help';
MLI18n::gi()->{'dummymodule_config_prepare__field__multimatching.itemsperpage__hint'} = 'dummymodule_config_prepare__field__multimatching.itemsperpage__hint';
MLI18n::gi()->{'dummymodule_config_prepare__field__prepare.manufacturerfallback__label'} = 'dummymodule_config_prepare__field__prepare.manufacturerfallback__label';
MLI18n::gi()->{'dummymodule_config_prepare__field__prepare.manufacturerfallback__help'} = 'dummymodule_config_prepare__field__prepare.manufacturerfallback__help';
MLI18n::gi()->{'dummymodule_config_prepare__field__quantity__label'} = 'dummymodule_config_prepare__field__quantity__label';
MLI18n::gi()->{'dummymodule_config_prepare__field__quantity__help'} = 'dummymodule_config_prepare__field__quantity__help';
MLI18n::gi()->{'dummymodule_config_prepare__field__leadtimetoship__label'} = 'dummymodule_config_prepare__field__leadtimetoship__label';
MLI18n::gi()->{'dummymodule_config_prepare__field__leadtimetoship__help'} = 'dummymodule_config_prepare__field__leadtimetoship__help';
MLI18n::gi()->{'dummymodule_config_prepare__field__checkin.skuasmfrpartno__label'} = 'dummymodule_config_prepare__field__checkin.skuasmfrpartno__label';
MLI18n::gi()->{'dummymodule_config_prepare__field__checkin.skuasmfrpartno__help'} = 'dummymodule_config_prepare__field__checkin.skuasmfrpartno__help';
MLI18n::gi()->{'dummymodule_config_prepare__field__checkin.skuasmfrpartno__valuehint'} = 'dummymodule_config_prepare__field__checkin.skuasmfrpartno__valuehint';
MLI18n::gi()->{'dummymodule_config_prepare__field__imagesize__label'} = 'dummymodule_config_prepare__field__imagesize__label';
MLI18n::gi()->{'dummymodule_config_prepare__field__imagesize__help'} = 'dummymodule_config_prepare__field__imagesize__help';
MLI18n::gi()->{'dummymodule_config_prepare__field__imagesize__hint'} = 'dummymodule_config_prepare__field__imagesize__hint';
MLI18n::gi()->{'dummymodule_config_price__legend__price'} = 'dummymodule_config_price__legend__price';
MLI18n::gi()->{'dummymodule_config_price__field__price__label'} = 'dummymodule_config_price__field__price__label';
MLI18n::gi()->{'dummymodule_config_price__field__price__hint'} = '';
MLI18n::gi()->{'dummymodule_config_price__field__price__help'} = 'dummymodule_config_price__field__price__help';
MLI18n::gi()->{'dummymodule_config_price__field__price.addkind__label'} = '';
MLI18n::gi()->{'dummymodule_config_price__field__price.addkind__hint'} = '';
MLI18n::gi()->{'dummymodule_config_price__field__price.factor__label'} = '';
MLI18n::gi()->{'dummymodule_config_price__field__price.factor__hint'} = '';
MLI18n::gi()->{'dummymodule_config_price__field__price.signal__label'} = 'dummymodule_config_price__field__price.signal__label';
MLI18n::gi()->{'dummymodule_config_price__field__price.signal__hint'} = 'dummymodule_config_price__field__price.signal__hint';
MLI18n::gi()->{'dummymodule_config_price__field__price.signal__help'} = 'dummymodule_config_price__field__price.signal__help';
MLI18n::gi()->{'dummymodule_config_price__field__priceoptions__label'} = 'dummymodule_config_price__field__priceoptions__label';
MLI18n::gi()->{'dummymodule_config_price__field__priceoptions__help'} = '{#i18n:configform_price_field_priceoptions_help#}';
MLI18n::gi()->{'dummymodule_config_price__field__priceoptions__hint'} = '';
MLI18n::gi()->{'dummymodule_config_price__field__price.group__label'} = '';
MLI18n::gi()->{'dummymodule_config_price__field__price.group__hint'} = '';
MLI18n::gi()->{'dummymodule_config_price__field__price.usespecialoffer__label'} = 'dummymodule_config_price__field__price.usespecialoffer__label';
MLI18n::gi()->{'dummymodule_config_price__field__price.usespecialoffer__hint'} = '';
MLI18n::gi()->{'dummymodule_config_price__field__exchangerate_update__label'} = 'dummymodule_config_price__field__exchangerate_update__label';
MLI18n::gi()->{'dummymodule_config_price__field__exchangerate_update__hint'} = 'dummymodule_config_price__field__exchangerate_update__hint';
MLI18n::gi()->{'dummymodule_config_price__field__exchangerate_update__help'} = '{#i18n:form_config_orderimport_exchangerate_update_help#}';
MLI18n::gi()->{'dummymodule_config_price__field__exchangerate_update__alert'} = '{#i18n:form_config_orderimport_exchangerate_update_alert#}';
MLI18n::gi()->{'dummymodule_config_sync__legend__sync'} = 'dummymodule_config_sync__legend__sync';
MLI18n::gi()->{'dummymodule_config_sync__field__stocksync.tomarketplace__label'} = 'dummymodule_config_sync__field__stocksync.tomarketplace__label';
MLI18n::gi()->{'dummymodule_config_sync__field__stocksync.tomarketplace__hint'} = '';
MLI18n::gi()->{'dummymodule_config_sync__field__stocksync.tomarketplace__help'} = 'dummymodule_config_sync__field__stocksync.tomarketplace__help';
MLI18n::gi()->{'dummymodule_config_sync__field__stocksync.frommarketplace__label'} = 'dummymodule_config_sync__field__stocksync.frommarketplace__label';
MLI18n::gi()->{'dummymodule_config_sync__field__stocksync.frommarketplace__hint'} = '';
MLI18n::gi()->{'dummymodule_config_sync__field__stocksync.frommarketplace__help'} = 'dummymodule_config_sync__field__stocksync.frommarketplace__help';
MLI18n::gi()->{'dummymodule_config_sync__field__inventorysync.price__label'} = 'dummymodule_config_sync__field__inventorysync.price__label';
MLI18n::gi()->{'dummymodule_config_sync__field__inventorysync.price__hint'} = '';
MLI18n::gi()->{'dummymodule_config_sync__field__inventorysync.price__help'} = 'dummymodule_config_sync__field__inventorysync.price__help';
MLI18n::gi()->{'dummymodule_config_orderimport__legend__importactive'} = 'dummymodule_config_orderimport__legend__importactive';
MLI18n::gi()->{'dummymodule_config_orderimport__legend__mwst'} = 'dummymodule_config_orderimport__legend__mwst';
MLI18n::gi()->{'dummymodule_config_orderimport__legend__orderstatus'} = 'dummymodule_config_orderimport__legend__orderstatus';
MLI18n::gi()->{'dummymodule_config_orderimport__field__orderstatus.sync__label'} = 'dummymodule_config_orderimport__field__orderstatus.sync__label';
MLI18n::gi()->{'dummymodule_config_orderimport__field__orderstatus.sync__hint'} = '';
MLI18n::gi()->{'dummymodule_config_orderimport__field__orderstatus.sync__help'} = 'dummymodule_config_orderimport__field__orderstatus.sync__help';
MLI18n::gi()->{'dummymodule_config_orderimport__field__orderstatus.shipped__label'} = 'dummymodule_config_orderimport__field__orderstatus.shipped__label';
MLI18n::gi()->{'dummymodule_config_orderimport__field__orderstatus.shipped__hint'} = '';
MLI18n::gi()->{'dummymodule_config_orderimport__field__orderstatus.shipped__help'} = 'dummymodule_config_orderimport__field__orderstatus.shipped__help';
MLI18n::gi()->{'dummymodule_config_orderimport__field__orderstatus.canceled__label'} = 'dummymodule_config_orderimport__field__orderstatus.canceled__label';
MLI18n::gi()->{'dummymodule_config_orderimport__field__orderstatus.canceled__hint'} = '';
MLI18n::gi()->{'dummymodule_config_orderimport__field__orderstatus.canceled__help'} = 'dummymodule_config_orderimport__field__orderstatus.canceled__help';
MLI18n::gi()->{'dummymodule_config_orderimport__field__orderimport.shop__label'} = '{#i18n:form_config_orderimport_shop_lable#}';
MLI18n::gi()->{'dummymodule_config_orderimport__field__orderimport.shop__hint'} = '';
MLI18n::gi()->{'dummymodule_config_orderimport__field__orderimport.shop__help'} = '{#i18n:form_config_orderimport_shop_help#}';
MLI18n::gi()->{'dummymodule_config_orderimport__field__orderimport.paymentmethod__label'} = 'dummymodule_config_orderimport__field__orderimport.paymentmethod__label';
MLI18n::gi()->{'dummymodule_config_orderimport__field__orderimport.paymentmethod__help'} = 'dummymodule_config_orderimport__field__orderimport.paymentmethod__help';
MLI18n::gi()->{'dummymodule_config_orderimport__field__orderimport.paymentmethod__hint'} = '';
MLI18n::gi()->{'dummymodule_config_orderimport__field__orderimport.shippingmethod__label'} = 'dummymodule_config_orderimport__field__orderimport.shippingmethod__label';
MLI18n::gi()->{'dummymodule_config_orderimport__field__orderimport.shippingmethod__help'} = 'dummymodule_config_orderimport__field__orderimport.shippingmethod__help';
MLI18n::gi()->{'dummymodule_config_orderimport__field__orderimport.shippingmethod__hint'} = '';
MLI18n::gi()->{'dummymodule_config_orderimport__field__mwstfallback__label'} = 'dummymodule_config_orderimport__field__mwstfallback__label';
MLI18n::gi()->{'dummymodule_config_orderimport__field__mwstfallback__hint'} = 'dummymodule_config_orderimport__field__mwstfallback__hint';
MLI18n::gi()->{'dummymodule_config_orderimport__field__mwstfallback__help'} = 'dummymodule_config_orderimport__field__mwstfallback__help';
MLI18n::gi()->{'dummymodule_config_orderimport__field__importactive__label'} = 'dummymodule_config_orderimport__field__importactive__label';
MLI18n::gi()->{'dummymodule_config_orderimport__field__importactive__hint'} = '';
MLI18n::gi()->{'dummymodule_config_orderimport__field__importactive__help'} = 'dummymodule_config_orderimport__field__importactive__help';
MLI18n::gi()->{'dummymodule_config_orderimport__field__import__label'} = '';
MLI18n::gi()->{'dummymodule_config_orderimport__field__import__hint'} = '';
MLI18n::gi()->{'dummymodule_config_orderimport__field__preimport.start__label'} = 'dummymodule_config_orderimport__field__preimport.start__label';
MLI18n::gi()->{'dummymodule_config_orderimport__field__preimport.start__hint'} = 'dummymodule_config_orderimport__field__preimport.start__hint';
MLI18n::gi()->{'dummymodule_config_orderimport__field__preimport.start__help'} = 'dummymodule_config_orderimport__field__preimport.start__help';
MLI18n::gi()->{'dummymodule_config_orderimport__field__customergroup__label'} = 'dummymodule_config_orderimport__field__customergroup__label';
MLI18n::gi()->{'dummymodule_config_orderimport__field__customergroup__hint'} = '';
MLI18n::gi()->{'dummymodule_config_orderimport__field__customergroup__help'} = 'dummymodule_config_orderimport__field__customergroup__help';
MLI18n::gi()->{'dummymodule_config_orderimport__field__orderstatus.open__label'} = 'dummymodule_config_orderimport__field__orderstatus.open__label';
MLI18n::gi()->{'dummymodule_config_orderimport__field__orderstatus.open__hint'} = '';
MLI18n::gi()->{'dummymodule_config_orderimport__field__orderstatus.open__help'} = 'dummymodule_config_orderimport__field__orderstatus.open__help';
MLI18n::gi()->{'dummymodule_config_orderimport__field__orderstatus.fba__label'} = 'dummymodule_config_orderimport__field__orderstatus.fba__label';
MLI18n::gi()->{'dummymodule_config_orderimport__field__orderstatus.fba__hint'} = '';
MLI18n::gi()->{'dummymodule_config_orderimport__field__orderstatus.fba__help'} = 'dummymodule_config_orderimport__field__orderstatus.fba__help';
MLI18n::gi()->{'dummymodule_config_orderimport__field__orderimport.fbapaymentmethod__label'} = 'dummymodule_config_orderimport__field__orderimport.fbapaymentmethod__label';
MLI18n::gi()->{'dummymodule_config_orderimport__field__orderimport.fbapaymentmethod__help'} = 'dummymodule_config_orderimport__field__orderimport.fbapaymentmethod__help';
MLI18n::gi()->{'dummymodule_config_orderimport__field__orderimport.fbapaymentmethod__hint'} = '';
MLI18n::gi()->{'dummymodule_config_orderimport__field__orderimport.fbashippingmethod__label'} = 'dummymodule_config_orderimport__field__orderimport.fbashippingmethod__label';
MLI18n::gi()->{'dummymodule_config_orderimport__field__orderimport.fbashippingmethod__help'} = 'dummymodule_config_orderimport__field__orderimport.fbashippingmethod__help';
MLI18n::gi()->{'dummymodule_config_orderimport__field__orderimport.fbashippingmethod__hint'} = '';
MLI18n::gi()->{'dummymodule_config_orderimport__field__orderstatus.carrier.default__label'} = 'dummymodule_config_orderimport__field__orderstatus.carrier.default__label';
MLI18n::gi()->{'dummymodule_config_orderimport__field__orderstatus.carrier.default__help'} = 'dummymodule_config_orderimport__field__orderstatus.carrier.default__help';
MLI18n::gi()->{'dummymodule_config_orderimport__field__orderstatus.carrier.additional__label'} = 'dummymodule_config_orderimport__field__orderstatus.carrier.additional__label';
MLI18n::gi()->{'dummymodule_config_orderimport__field__orderstatus.carrier.additional__help'} = 'dummymodule_config_orderimport__field__orderstatus.carrier.additional__help';
MLI18n::gi()->{'dummymodule_config_orderimport__field__orderstatus.cancelled__label'} = 'dummymodule_config_orderimport__field__orderstatus.cancelled__label';
MLI18n::gi()->{'dummymodule_config_orderimport__field__orderstatus.cancelled__hint'} = '';
MLI18n::gi()->{'dummymodule_config_orderimport__field__orderstatus.cancelled__help'} = 'dummymodule_config_orderimport__field__orderstatus.cancelled__help';
MLI18n::gi()->{'dummymodule_config_emailtemplate__legend__mail'} = 'dummymodule_config_emailtemplate__legend__mail';
MLI18n::gi()->{'dummymodule_config_emailtemplate__field__mail.send__label'} = 'dummymodule_config_emailtemplate__field__mail.send__label';
MLI18n::gi()->{'dummymodule_config_emailtemplate__field__mail.send__help'} = 'dummymodule_config_emailtemplate__field__mail.send__help';
MLI18n::gi()->{'dummymodule_config_emailtemplate__field__mail.originator.name__label'} = 'dummymodule_config_emailtemplate__field__mail.originator.name__label';
MLI18n::gi()->{'dummymodule_config_emailtemplate__field__mail.originator.adress__label'} = 'dummymodule_config_emailtemplate__field__mail.originator.adress__label';
MLI18n::gi()->{'dummymodule_config_emailtemplate__field__mail.subject__label'} = 'dummymodule_config_emailtemplate__field__mail.subject__label';
MLI18n::gi()->{'dummymodule_config_emailtemplate__field__mail.content__label'} = 'dummymodule_config_emailtemplate__field__mail.content__label';
MLI18n::gi()->{'dummymodule_config_emailtemplate__field__mail.content__hint'} = 'dummymodule_config_emailtemplate__field__mail.content__hint';
MLI18n::gi()->{'dummymodule_config_emailtemplate__field__mail.copy__label'} = 'dummymodule_config_emailtemplate__field__mail.copy__label';
MLI18n::gi()->{'dummymodule_config_emailtemplate__field__mail.copy__help'} = 'dummymodule_config_emailtemplate__field__mail.copy__help';

MLI18n::gi()->add('dummymodule_config_prepare__field__b2bactive', array(
    'label' => 'Business Activated',
    'help' => 'If enabled, specific settings below will be used when uploading product to Amazon. <b>Please make sure that your account is enabled for Amazon Business services.</b> Otherwise, you might experience errors during upload if this option is enabled.',
    'notification' => 'In order to use Amazon Business features you need to have your 
Amazon account activated for this. <b>Please make sure that your account is enabled for Amazon Business services.</b> 
Otherwise, you might experience errors during upload if this option is enabled.
<br>To upgrade your account, please follow instructions on 
<a href="https://sellercentral.dummymodule.de/business/b2bregistration" target="_blank">this page</a>.',
    'values' => array(
        'true' => 'Yes',
        'false' => 'No',
    ),
));
MLI18n::gi()->add('dummymodule_config_prepare__field__b2b.tax_code', array(
    'label' => 'Business Tax Matching',
    'hint' => '',
    'matching' => array(
        'titlesrc' => 'Shop Tax Classes',
        'titledst' => 'Amazon Business Tax Codes',
    )
));
MLI18n::gi()->add('dummymodule_config_prepare__field__b2b.tax_code_container', array(
    'label' => 'Business Tax Matching per Amazon Category',
    'hint' => '',
));
MLI18n::gi()->add('dummymodule_config_prepare__field__b2b.tax_code_specific', array(
    'label' => '',
    'hint' => '',
    'matching' => array(
        'titlesrc' => 'Shop Tax Classes',
        'titledst' => 'Amazon Business Tax Codes',
    )
));
MLI18n::gi()->add('dummymodule_config_prepare__field__b2b.tax_code_category', array(
    'label' => '',
    'hint' => '',
));
MLI18n::gi()->add('dummymodule_config_prepare__field__b2bsellto', array(
    'label' => 'Sell To',
    'help' => 'If <i>B2B Only</i> is selected, uploaded products with this option will be visible only for 
        Business customers on Amazon. Otherwise, products will be available for both regular and business customers.',
    'values' => array(
        'b2b_b2c' => 'B2B and B2C',
        'b2b_only' => 'B2B Only',
    ),
));
MLI18n::gi()->add('dummymodule_config_prepare__field__b2b.price', array(
    'label' => 'Business Price',
    'help' => 'Please enter a price markup or markdown, either in percentage or fixed amount. 
        Use a minus sign (-) before the amount to denote markdown.',
));
MLI18n::gi()->add('dummymodule_config_prepare__field__b2b.price.addkind', array(
    'label' => '',
    'hint' => '',
));
MLI18n::gi()->add('dummymodule_config_prepare__field__b2b.price.factor', array(
    'label' => '',
    'hint' => '',
));
MLI18n::gi()->add('dummymodule_config_prepare__field__b2b.price.signal', array(
    'label' => 'Decimal Amount',
    'hint' => 'Decimal Amount',
    'help' => 'This textfield shows the decimal value that will appear in the item price on Amazon.<br/><br/>
        <strong>Example:</strong> <br>
        Value in textfeld: 99 <br>
        Original price: 5.58 <br>
        Final amount: 5.99 <br><br>
        This function is useful when marking the price up or down***. <br>
        Leave this field empty if you do not wish to set any decimal amount. <br>
        The format requires a maximum of 2 numbers.'
));
MLI18n::gi()->add('dummymodule_config_prepare__field__b2b.priceoptions', array(
    'label' => 'Business Price Options',
));
MLI18n::gi()->add('dummymodule_config_prepare__field__b2b.price.group', array(
    'label' => '',
    'hint' => '',
));
MLI18n::gi()->add('dummymodule_config_prepare__field__b2b.price.usespecialoffer', array(
    'label' => 'Use special offer prices',
));
MLI18n::gi()->add('dummymodule_config_prepare__field__b2bdiscounttype', array(
    'label' => 'Quantity Discount Type',
    'help' => '<b>Quantity Discount</b><br>
        Quantity Discount represents tiered discounts available to Amazon Business Customers 
        for higher-volume purchases. Sellers in the Amazon Business Seller Program specify tiers 
        for Quantity Pricing. Option "percent" means that specify percent of discount will be applied 
        to purchases that include specified quantity.<br><br>
        <b>Example</b>: 
        If product costs $100 and discount type is "Percent", applied discounts for <b>business customers</b>
        could be set like this: 
        <table><tr>
            <th style="background-color: #ddd;">Quantity</th>
            <th style="background-color: #ddd;">Discount</th>
            <th style="background-color: #ddd;">Final price per product</th>
        <tr><td>5 (or more)</td><td style="text-align: right;">10</td><td style="text-align: right;">$90</td></tr>
        <tr><td>8 (or more)</td><td style="text-align: right;">12</td><td style="text-align: right;">$88</td></tr>
        <tr><td>12 (or more)</td><td style="text-align: right;">15</td><td style="text-align: right;">$85</td></tr>
        <tr><td>20 (or more)</td><td style="text-align: right;">20</td><td style="text-align: right;">$80</td></tr>
        </table>',
    'values' => array(
        '' => 'Do not use',
        'percent' => 'Percent',
    ),
));
MLI18n::gi()->{'dummymodule_config_prepare__field__b2bdiscounttier1__label'} = 'Quantity Discount Tier 1';
MLI18n::gi()->{'dummymodule_config_prepare__field__b2bdiscounttier2__label'} = 'Quantity Discount Tier 2';
MLI18n::gi()->{'dummymodule_config_prepare__field__b2bdiscounttier3__label'} = 'Quantity Discount Tier 3';
MLI18n::gi()->{'dummymodule_config_prepare__field__b2bdiscounttier4__label'} = 'Quantity Discount Tier 4';
MLI18n::gi()->{'dummymodule_config_prepare__field__b2bdiscounttier5__label'} = 'Quantity Discount Tier 5';
MLI18n::gi()->{'dummymodule_config_prepare__field__b2bdiscounttier1quantity__label'} = 'Quantity';
MLI18n::gi()->{'dummymodule_config_prepare__field__b2bdiscounttier2quantity__label'} = 'Quantity';
MLI18n::gi()->{'dummymodule_config_prepare__field__b2bdiscounttier3quantity__label'} = 'Quantity';
MLI18n::gi()->{'dummymodule_config_prepare__field__b2bdiscounttier4quantity__label'} = 'Quantity';
MLI18n::gi()->{'dummymodule_config_prepare__field__b2bdiscounttier5quantity__label'} = 'Quantity';
MLI18n::gi()->{'dummymodule_config_prepare__field__b2bdiscounttier1discount__label'} = 'Discount';
MLI18n::gi()->{'dummymodule_config_prepare__field__b2bdiscounttier2discount__label'} = 'Discount';
MLI18n::gi()->{'dummymodule_config_prepare__field__b2bdiscounttier3discount__label'} = 'Discount';
MLI18n::gi()->{'dummymodule_config_prepare__field__b2bdiscounttier4discount__label'} = 'Discount';
MLI18n::gi()->{'dummymodule_config_prepare__field__b2bdiscounttier5discount__label'} = 'Discount';