<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Fyndiq_CheckinForm__Price'} = 'Prix';
MLI18n::gi()->{'Fyndiq_CheckinForm__Amount'} = 'Quantité';
MLI18n::gi()->{'Fyndiq_CheckinForm__ShippingTime'} = 'Livraison (en jours)';
MLI18n::gi()->{'Fyndiq_CheckinForm__ShopPrice'} = 'Boutique';
MLI18n::gi()->{'Fyndiq_CheckinForm__SuggestedPrice'} = 'Calculé (d\'après vos configurations)';
MLI18n::gi()->{'Fyndiq_CheckinForm__HitPrice'} = 'Prix "Hit"';
MLI18n::gi()->{'Fyndiq_CheckinForm__AvailibleAmount'} = 'Disponible';
MLI18n::gi()->{'Fyndiq_CheckinForm__SuggestedAmount'} = 'Calculé (d\'après vos configurations)';
MLI18n::gi()->{'Fyndiq_CheckinForm__Condition'} = 'État de l\'article';
MLI18n::gi()->{'Fyndiq_CheckinForm__ListingType'} = 'Type de listing';
MLI18n::gi()->{'Fyndiq_CheckinForm__Conditions__new'} = 'Neuf';
MLI18n::gi()->{'Fyndiq_CheckinForm__Conditions__not_specified'} = 'Pas spécifié';
MLI18n::gi()->{'Fyndiq_CheckinForm__Conditions__used'} = 'D\'occasion';
MLI18n::gi()->{'Fyndiq_CheckinForm__BuyingMode'} = 'Mode achat';
MLI18n::gi()->{'Fyndiq_CheckinForm__BuyingModes__buy_it_now'} = 'Achat directe ';
MLI18n::gi()->{'Fyndiq_CheckinForm__BuyingModes__auction'} = 'Enchères';
MLI18n::gi()->{'Fyndiq_CheckinForm__BuyingModes__classified'} = 'Classé';
MLI18n::gi()->{'Fyndiq_CheckinForm__ShippingMode'} = 'Mode de livraison';
MLI18n::gi()->{'Fyndiq_CheckinForm__ShippingModes__custom'} = 'Personnalisé';
MLI18n::gi()->{'Fyndiq_CheckinForm__ShippingModes__not_specified'} = 'Pas spécifié';
