<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'fyndiq_prepare_form__legend__details'} = 'Fiche Produit';
MLI18n::gi()->{'fyndiq_prepare_form__legend__delivery'} = 'Livraison';
MLI18n::gi()->{'fyndiq_prepare_form__legend__categories'} = 'Catégorie';
MLI18n::gi()->{'fyndiq_prepare_form__field__categories__label'} = 'Catégories Fyndiq';
MLI18n::gi()->{'fyndiq_prepare_form__field__primarycategory__label'} = '1. Catégorie de la place de marché';
MLI18n::gi()->{'fyndiq_prepare_form__field__catattributes__label'} = 'Attributs de catégorie';
MLI18n::gi()->{'fyndiq_prepare_form__field__itemtitle__label'} = 'Tittre';
MLI18n::gi()->{'fyndiq_prepare_form__field__itemtitle__hint'} = 'Tittre 64 caractère max.';
MLI18n::gi()->{'fyndiq_prepare_form__field__description__label'} = 'Description';
MLI18n::gi()->{'fyndiq_prepare_form__field__description__hint'} = '4096 caractères maximums (HTML inclus).';
MLI18n::gi()->{'fyndiq_prepare_form__field__brand__label'} = 'Marque';
MLI18n::gi()->{'fyndiq_prepare_form__field__images__label'} = 'Images de l\'article';
MLI18n::gi()->{'fyndiq_prepare_form__field__comparasionunit__label'} = 'Élement de comparaison';
MLI18n::gi()->{'fyndiq_prepare_form__field__location__label'} = 'Emplacement';
MLI18n::gi()->{'fyndiq_prepare_form__field__price__label'} = 'Prix';
MLI18n::gi()->{'fyndiq_prepare_form__field__shippingtime__label'} = 'Délai de livraison';
MLI18n::gi()->{'fyndiq_prepare_form__field__shippingcost__label'} = 'Frais de port (EUR)';
MLI18n::gi()->{'fyndiq_prepareform_max_length_part1'} = 'La limiteLa longueur maximale de';
MLI18n::gi()->{'fyndiq_prepareform_max_length_part2'} = 'l\'attribut est de';
MLI18n::gi()->{'fyndiq_prepare_form_category'} = 'Le choix d\'une catégorie est obligatoire.';
MLI18n::gi()->{'fyndiq_prepare_form_itemtitle'} = 'L\'attribut "tittre" est un champs obligatoire est doit contenir entre 5 et 64 caractères.';
MLI18n::gi()->{'fyndiq_prepare_form_description'} = 'La description est un champs obligatoire et doit contenir 10 à 4096 caractères.';
MLI18n::gi()->{'fyndiq_prepareform_category_attribute'} = 'Les attributs sont obligatoire.';
MLI18n::gi()->{'fyndiq_category_no_attributes'} = 'Les déclinaisons ne sont pas prévues pour cette catégorie';
