<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'FYNDIQ_ML_LABEL_ARTICLE_SKU'} = 'Numéro SKU';
MLI18n::gi()->{'FYNDIQ_ML_LABEL_ARTICLE_NAME'} = 'Tittre sur Fyndiq';
MLI18n::gi()->{'FYNDIQ_ML_LABEL_ARTICLE_SHOP_PREIS'} = 'Prix dans votre boutique';
MLI18n::gi()->{'FYNDIQ_ML_LABEL_ARTICLE_MARKETPLACE_PREIS'} = 'Prix sur place de marché';
MLI18n::gi()->{'fyndiq_inventory_listing_status'} = 'Statut';
MLI18n::gi()->{'fyndiq_inventory_reject_message'} = 'Veuillez contacter Fyndiq.';
MLI18n::gi()->{'Fyndiq_Productlist_Cell_aPreparedStatus__OK__title'} = 'Préparé avec succès';
MLI18n::gi()->{'Fyndiq_Productlist_Cell_aPreparedStatus__ERROR__title'} = 'Mal préparé ';
MLI18n::gi()->{'Fyndiq_Productlist_Cell_aPreparedStatus__OPEN__title'} = 'Articles préparés non vérifiés';
MLI18n::gi()->{'Fyndiq_Productlist_Filter_aPreparedStatus__OK'} = 'Préparé avec succès';
MLI18n::gi()->{'Fyndiq_Productlist_Filter_aPreparedStatus__ERROR'} = 'Mal préparé ';
MLI18n::gi()->{'Fyndiq_Productlist_Filter_aPreparedStatus__OPEN'} = 'Articles préparés non vérifiés';
