<?php
/*
 * 888888ba                 dP  .88888.                    dP
 * 88    `8b                88 d8'   `88                   88
 * 88aaaa8P' .d8888b. .d888b88 88        .d8888b. .d8888b. 88  .dP  .d8888b.
 * 88   `8b. 88ooood8 88'  `88 88   YP88 88ooood8 88'  `"" 88888"   88'  `88
 * 88     88 88.  ... 88.  .88 Y8.   .88 88.  ... 88.  ... 88  `8b. 88.  .88
 * dP     dP `88888P' `88888P8  `88888'  `88888P' `88888P' dP   `YP `88888P'
 *
 *                          m a g n a l i s t e r
 *                                      boost your Online-Shop
 *
 * -----------------------------------------------------------------------------
 * (c) 2010 - 2021 RedGecko GmbH -- http://www.redgecko.de
 *     Released under the MIT License (Expat)
 * -----------------------------------------------------------------------------
 */

/* Autogenerated file. Do not change! */

MLI18n::gi()->{'etsy_config_account_title'} = 'Login Details';
MLI18n::gi()->{'etsy_config_account_prepare'} = 'Item preparation';
MLI18n::gi()->{'etsy_config_account_price'} = 'Price calculation';
MLI18n::gi()->{'etsy_config_account_sync'} = 'Synchronization';
MLI18n::gi()->{'etsy_config_account_orderimport'} = 'Order import';

MLI18n::gi()->{'etsy_configform_sync_values'} = array(
    'no' => '{#i18n:configform_sync_value_no#}',
    'auto_zero_stock' => 'Synchronisation automatique stocks zéro inclus (recommandé)',
    'auto' => 'Synchronisation automatique sans stocks zéro',
);

MLI18n::gi()->{'etsy_configform_sync_nozerostock_popup_label'} = 'Synchronisation automatique sans stocks zéro';
MLI18n::gi()->{'etsy_configform_sync_nozerostock_popup_text'} = 'Les produits dont le stock dans votre boutique est réduit à 0 seront désactivés sur Etsy. Cela permet d\'éviter de vous exposer à des frais non intentionnels d’Etsy.';
MLI18n::gi()->{'etsy_configform_sync_zerostock_popup_label'} = 'Synchronisation automatique stocks zéro inclus (recommandé)';
MLI18n::gi()->{'etsy_configform_sync_zerostock_popup_text'} = 'Cette option active ou désactive également vos offres sur Etsy si le stock dans votre boutique est supérieur à “0” ou inférieur “1”. Etsy vous facturera pour chaque réactivation.';

MLI18n::gi()->{'etsy_config_carrier_option_group_additional_option'} = 'Additional option:';
MLI18n::gi()->{'etsy_config_carrier_option_group_marketplace_carrier'} = 'Select Marketplace Supported Carrier:';
MLI18n::gi()->{'etsy_config_free_text_attributes_opt_group'} = 'Free text fields';
MLI18n::gi()->{'etsy_config_free_text_attributes_opt_group_value'} = 'Match it to free text field on specific order';
MLI18n::gi()->{'etsy_config_carrier_option_matching_option'} = 'Match marketplace supported carrier with carriers defined in shop-system';
MLI18n::gi()->{'etsy_config_carrier_matching_title_marketplace_carrier'} = 'Marketplace supported carriers';
MLI18n::gi()->{'etsy_config_carrier_matching_title_shop_carrier'} = 'Carriers defined in the shop-system (shipping module)';
