<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'sModuleNameEtsy'} = 'Etsy';
MLI18n::gi()->{'etsy_prepare_description_not_valid'} = 'Item description is too long. Maximum number of characters is 63000.';
MLI18n::gi()->{'etsy_prepare_images_not_valid'} = 'The picture is too big. The maximum allowed image size is 3000 x 3000 px.';
MLI18n::gi()->{'etsy_prepare_images_not_exist'} = 'There must be at least one image for the item !';
MLI18n::gi()->{'etsy_prepare_description_not_exist'} = 'Item description is too short.';
MLI18n::gi()->{'etsy_prepare_price_not_valid'} = 'Minimum item price on Etsy is 0.17£';
MLI18n::gi()->{'etsy_prepare_quantity_not_valid'} = 'The stock for a product must not be larger than 999.';

MLI18n::gi()->{'etsy_inventory_listing_status_new'} = 'Product will be created';
MLI18n::gi()->{'etsy_inventory_listing_status_active'} = 'Actif';
MLI18n::gi()->{'etsy_inventory_listing_status_inactive'} = 'Inactif';
MLI18n::gi()->{'etsy_inventory_listing_status_expired'} = 'Expired';
MLI18n::gi()->{'etsy_inventory_listing_status_draft'} = 'Draft';
MLI18n::gi()->{'etsy_inventory_listing_status_sold_out'} = 'Sold Out';

MLI18n::gi()->{'etsy_checkin_purge_popup_text'} = '
<p><strong>Veuillez noter que :</strong> Vous &ecirc;tes sur le point de remplacer compl&egrave;tement votre inventaire sur Etsy. Ce processus supprime d\'abord compl&egrave;tement votre inventaire du march&eacute; et le remplace ensuite par les &eacute;l&eacute;ments s&eacute;lectionn&eacute;s ici.</p>
<p>Etsy facture des frais de mise en place pour la cr&eacute;ation de nouvelles offres. Veuillez contacter Etsy Support si vous avez des questions concernant votre tarif Etsy.</p>
<p>Vous &ecirc;tes s&ucirc;r de vouloir continuer ?</p>
';
MLI18n::gi()->{'etsy_checkin_popup_text'} = '<p><strong>Veuillez noter que :</strong> Etsy facture des frais de mise en place pour la cr&eacute;ation de nouvelles offres. Veuillez contacter Etsy Support si vous avez des questions concernant votre tarif Etsy.</p>';
