<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'MercadoLivre_CheckinForm__Price'} = 'Prix';
MLI18n::gi()->{'MercadoLivre_CheckinForm__Amount'} = 'Quantité';
MLI18n::gi()->{'MercadoLivre_CheckinForm__ShippingTime'} = 'Délais de livraison (en jours)';
MLI18n::gi()->{'MercadoLivre_CheckinForm__ShopPrice'} = 'Boutique';
MLI18n::gi()->{'MercadoLivre_CheckinForm__SuggestedPrice'} = 'Calculé (selon les configuration)';
MLI18n::gi()->{'MercadoLivre_CheckinForm__HitPrice'} = 'Prix hit';
MLI18n::gi()->{'MercadoLivre_CheckinForm__AvailibleAmount'} = 'Disponible';
MLI18n::gi()->{'MercadoLivre_CheckinForm__SuggestedAmount'} = 'Calculé (d\'après la configuration)';
MLI18n::gi()->{'MercadoLivre_CheckinForm__Condition'} = 'État de l\'article';
MLI18n::gi()->{'MercadoLivre_CheckinForm__ListingType'} = 'Type de listing';
MLI18n::gi()->{'MercadoLivre_CheckinForm__Conditions__new'} = 'Neuf';
MLI18n::gi()->{'MercadoLivre_CheckinForm__Conditions__not_specified'} = 'Pas spécifié';
MLI18n::gi()->{'MercadoLivre_CheckinForm__Conditions__used'} = 'D\'occasion';
MLI18n::gi()->{'MercadoLivre_CheckinForm__BuyingMode'} = 'Mode d\'achat';
MLI18n::gi()->{'MercadoLivre_CheckinForm__BuyingModes__buy_it_now'} = 'Achat direct';
MLI18n::gi()->{'MercadoLivre_CheckinForm__BuyingModes__auction'} = 'Vente aux enchères';
MLI18n::gi()->{'MercadoLivre_CheckinForm__BuyingModes__classified'} = 'Classé';
MLI18n::gi()->{'MercadoLivre_CheckinForm__ShippingMode'} = 'Mode de livraison';
MLI18n::gi()->{'MercadoLivre_CheckinForm__ShippingModes__custom'} = 'Personnalisé';
MLI18n::gi()->{'MercadoLivre_CheckinForm__ShippingModes__not_specified'} = 'pas spécifié';
