<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'mercadolivre_prepare_form__legend__details'} = 'Fiche Produit';
MLI18n::gi()->{'mercadolivre_prepare_form__legend__categories'} = 'Catégories MercadoLivre';
MLI18n::gi()->{'mercadolivre_prepare_form__legend__variationmatching__0'} = '{#i18n:attributes_matching_required_attributes#}';
MLI18n::gi()->{'mercadolivre_prepare_form__legend__variationmatching__1'} = '{#i18n:attributes_matching_title#}';
MLI18n::gi()->{'mercadolivre_prepare_form__legend__variationmatchingoptional__0'} = '{#i18n:attributes_matching_optional_attributes#}';
MLI18n::gi()->{'mercadolivre_prepare_form__legend__variationmatchingoptional__1'} = '{#i18n:attributes_matching_title#}';
MLI18n::gi()->{'mercadolivre_prepare_form__legend__configmatching'} = 'Configuration MercadoLivre';
MLI18n::gi()->{'mercadolivre_prepare_form__field__categories__label'} = 'Catégories MercadoLivre';
MLI18n::gi()->{'mercadolivre_prepare_form__field__primarycategory__label'} = '1. Catégorie de la place de marché';
MLI18n::gi()->{'mercadolivre_prepare_form__field__currency__label'} = 'Devise';
MLI18n::gi()->{'mercadolivre_prepare_form__field__itemcondition__label'} = 'État de l\'article';
MLI18n::gi()->{'mercadolivre_prepare_form__field__listingtype__label'} = 'Type de listing';
MLI18n::gi()->{'mercadolivre_prepare_form__field__buyingmode__label'} = 'Mode d\'achat';
MLI18n::gi()->{'mercadolivre_prepare_form__field__shippingmode__label'} = 'Mode de livraison';
MLI18n::gi()->{'mercadolivre_prepare_form__field__webshopattribute__label'} = 'Attribut de votre Boutique';
MLI18n::gi()->{'mercadolivre_prepare_form__field__attributematching__matching__titlesrc'} = 'Valeur dans la boutique';
MLI18n::gi()->{'mercadolivre_prepare_form__field__attributematching__matching__titledst'} = 'Valeur MercadoLivre';
MLI18n::gi()->{'mercadolivre_prepareform_max_length_part1'} = 'Longueur maximale de';
MLI18n::gi()->{'mercadolivre_prepareform_max_length_part2'} = 'L\'attribut est';
MLI18n::gi()->{'mercadolivre_prepareform_reqired_fieds'} = 'Remarque : Les champs marqués <span class="bull">•</span> sont à remplir obligatoirement.';
