<?php
/* Autogenerated file. Do not change! */
MLI18n::gi()->{'form_config_orderimport_exchangerate_update_help'} = 'form_config_orderimport_exchangerate_update_help';
MLI18n::gi()->{'form_config_orderimport_exchangerate_update_alert'} = 'form_config_orderimport_exchangerate_update_alert';
