<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Magento2_Orderimport_CountryCodeIsEmptyError'} = 'Magento2_Orderimport_CountryCodeIsEmptyError';
MLI18n::gi()->{'Magento2_Orderimport_CountryCodeDontExistsError'} = 'Magento2_Orderimport_CountryCodeDontExistsError';
MLI18n::gi()->{'shopware_orderstatus_carrier_defaultField_value_shippingname'} = 'shopware_orderstatus_carrier_defaultField_value_shippingname';