<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Magento2_Productlist_Filter_sStatus'} = 'Situação';
MLI18n::gi()->{'Magento2_Productlist_Filter_sActive'} = 'ativo';
MLI18n::gi()->{'Magento2_Productlist_Filter_sInactive'} = 'inativo';
MLI18n::gi()->{'Magento2_Productlist_Filter_sManufacturer'} = 'Fabricante';
MLI18n::gi()->{'Magento2_Productlist_Filter_sManufacturerId'} = 'Número do fabricante';
MLI18n::gi()->{'Magento2_Productlist_Filter_sEan'} = 'EAN';
MLI18n::gi()->{'Magento2_Productlist_Filter_sCategory'} = 'Categoria';

MLI18n::gi()->{'Magento2_Productlist_Filter_sProductType'} = 'Product type';
MLI18n::gi()->{'Magento2_Productlist_Filter_sConfigurable'} = 'Configurable';
MLI18n::gi()->{'Magento2_Productlist_Filter_sSimple'} = 'Simple';
MLI18n::gi()->{'Magento2_Productlist_Filter_sDownloadable'} = 'Downloadable';
MLI18n::gi()->{'Magento2_Productlist_Filter_sVirtual'} = 'Virtual';
