<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'check24_prepare_form__legend__details'} = 'Détails sur l\'article';
MLI18n::gi()->{'check24_prepare_form__legend__categories'} = 'Catégorie CHECK24';
MLI18n::gi()->{'check24_prepare_form__field__shippingtime__label'} = 'Délais de livraison';
MLI18n::gi()->{'check24_prepare_form__field__shippingtime__hint'} = '';
MLI18n::gi()->{'check24_prepare_form__field__shippingcost__label'} = 'Frais de port';
MLI18n::gi()->{'check24_prepare_form__field__shippingcost__hint'} = '';
