<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'ebay_config_orderimport__field__orderimport.shippingmethod__label'} = 'Mode d\'expédition de la commande';
MLI18n::gi()->{'ebay_config_orderimport__field__orderimport.shippingmethod__help'} = '<p>Mode d\'expédition assigné à toutes les commandes émanant de eBay, à l\'importation de la commande.</p>
<p>Choisissez ici les modes d\'expédition disponibles, pour votre boutique. Le contenu de la liste de choix est défini par vous-même. Pour cela, rendez-vous dans le menu Prestashop-Admin > expédition > du service d\'expédition.</p>
<p>Ce réglage est important pour l\'impression de bons de livraison et de factures et pour le traitement de la commande.</p>';
MLI18n::gi()->{'ebay_config_orderimport__field__orderimport.shippingmethod__hint'} = '';
