<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'sAddAewShopAttributeInstruction'} = 'Afin que les donnés puissent-être transmises, veuillez apparier (matcher) les valeurs suivantes avec les attributs de votre boutique. Les attibuts peuvent être définis en vous rendant dans le menu latéral du backoffice de PrestShop en cliquant sur : "catalogue" > "Attributs des produits". Le bouton "plus" permet d\'ajouter des attributs.<br />Vous pouvez modifier les attributs d\'un produit particulier sous : "catalogue" > "produits" > "modifier" > "Caractéristiques"';
