<?php
/**
 * 888888ba                 dP  .88888.                    dP
 * 88    `8b                88 d8'   `88                   88
 * 88aaaa8P' .d8888b. .d888b88 88        .d8888b. .d8888b. 88  .dP  .d8888b.
 * 88   `8b. 88ooood8 88'  `88 88   YP88 88ooood8 88'  `"" 88888"   88'  `88
 * 88     88 88.  ... 88.  .88 Y8.   .88 88.  ... 88.  ... 88  `8b. 88.  .88
 * dP     dP `88888P' `88888P8  `88888'  `88888P' `88888P' dP   `YP `88888P'
 *
 *                          m a g n a l i s t e r
 *                                      boost your Online-Shop
 *
 * -----------------------------------------------------------------------------
 * (c) 2010 - 2020 RedGecko GmbH -- http://www.redgecko.de
 *     Released under the MIT License (Expat)
 * -----------------------------------------------------------------------------
 */

/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Amazon_Orderlist_Customer_Name_Label'} = 'Nom de client';
MLI18n::gi()->{'ML_Amazon_Shippinglabel'} = 'Service Achat de l\'affranchissement';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Overview'} = 'Suivi du colis';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Upload'} = 'Demander l’achat de l’affranchissement';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Upload_Orderlist'} = 'Commande';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Upload_Form'} = 'Information sur le paquet';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Upload_Shippingmethod'} = 'Afficher le mode d\'expédition';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Upload_Summary'} = 'Résumé';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Orderlist_PurchaseDate'} = 'Délai de commande';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Orderlist_AmazonOrderID'} = 'N°  de commande Amazon';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Orderlist_ShipmentId'} = 'ID de livraison';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Orderlist_BuyerName'} = 'Client';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Orderlist_Price'} = 'Montant total';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Orderlist_CurrentStatus'} = 'Statut de commande Amazon';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Orderlist_CurrentStatus_Open'} = 'Ouvert';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Orderlist_CurrentStatus_Shipped'} = 'Envoyer';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Orderlist_CurrentStatus_Cancelled'} = 'Annuler';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Orderlist_ShippingStatus'} = 'Affranchissement réquisitionné';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Package_Length'} = 'Longueur';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Package_Width'} = 'Largeur';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Package_Height'} = 'Hauteur';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Form_Customer_Name_Label'} = 'Nom du client';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Form_PrductName'} = 'Produit';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Form_Sent'} = 'L\'article à été envoyé';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Form_Quantity'} = 'Article emballé';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Form_Shipping_Information_Label'} = 'Information d\'expédition';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Form_Package_Size_Label'} = 'Dimention du paquet';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Form_Package_Dimension_Label'} = 'Poids du paquet';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Form_Package_Carrierwillpickup_Label'} = 'Enlévement du paquet';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Form_Package_Deliveryexpierience_Label'} = 'Condition d\'expédition';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Form_Package_SenderAddress_Label'} = 'Adresse d\'expédition';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Shippingmethod_ExtraditionWarning_Label'} = 'Bon de livraisomn';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_ShippingMethod_ShippingMethodOfCutomer_Label'} = 'Mode de livraison choisi par le client.';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_ShippingMethod_Disclaimer_Label'} = 'Condition légale';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_ShippingMethod_StandardService_Label'} = 'Déterminer les options standard d\'expédition';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Summary_Statistic'} = '{1} sur {2} commande on été envoié à la place de marché.';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Receiver'} = 'Envoyé à';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_ShippingDate'} = 'Date d\'envoie';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Weight'} = 'poids';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_CarrierName'} = 'Transporteur';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_UnitPrice'} = 'Prix plancher';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_TotalPrice'} = 'Somme des frais d\'envois';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Form_CarrierName'} = 'Transporteurs';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Shippinmethod_DeliveryTime'} = 'Date de livraison estimée';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Shippinmethod_Amount'} = 'Coût';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Shippinmethod_Comment'} = 'Commentaire';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_ShippingMethod_Warning_ShippingServiceNotAvailable'} = 'Les prestataires de transport disponibles actuellement ne peuvent malheureusement pas offrir de mode d\'expédition convenable pour ces indications.';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Overview_DeleteShippingLable'} = 'Supprimer l\'étiquette';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Overview_CancelShippingLable'} = 'Annuler l\'étiquette';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Confirm'} = 'Validez et confirmez vos achats';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Download'} = 'Téléchargez les étiquettes d\'envoi';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Cancel'} = 'Annulez';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Delete'} = 'Supprimez';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Filter_Status_Default'} = 'Filtre (paiement demandé)';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Filter_Status_Full'} = 'Complètement ';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Filter_Status_Partly'} = 'partiellement';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Filter_Status_Not'} = 'Sans';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Filter_OrderType_Default'} = 'Filtre (FulfillmentChannel)';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Filter_OrderType_MFN'} = 'Standard (MFN)';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Filter_OrderType_MFNPrime'} = 'Prime par le vendeur (MFN-Prime)';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Filter_OrderType_Business'} = 'Amazon Business (B2B)';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Filter_OrderType_FBA'} = 'Expédition par Amazon (FBA)';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Filter_OrderType_Prime_SameDay'} = 'Prime Same Day';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Filter_OrderType_Prime_NextDay'} = 'Prime Next Day';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Filter_OrderType_Prime_SecondDay'} = 'Prime Second Day';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Form_Weight_Notice'} = 'Poids des articles plus le poids du matériel d\'emballage (Tare)';
MLI18n::gi()->{'ML_Amazon_Shipping_Success'} = '';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Popup_Afterconfirm_Infocontent'} = 'Votre paiement à été enregistré les étiquettes d\'expédition sont à votre disposition.<br>Pour les télécharger, cliquer sur le bouton «TÉLÉCHARGEMENT».<br> Sous la rubrique « aperçu de paquet » vous pouvez de nouveau demander des étiquettes.';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Overview_Popup_Afterconfirm_Infocontent'} = 'Votre étiquette d\'expédition est prête, pour la télécharger, cliquer sur le bouton «TÉLÉCHARGEMENT».';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Overview_CreatedDate'} = 'Affranchissement réquisitionné';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Overview_SenderAndTrackingId'} = 'Code de suivi / transporteur';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Download_Title'} = 'Télécharger les tarifs de livraison';
MLI18n::gi()->{'Orderlist_Cell_aToMagnalisterSelection_selectedOrdersCountInfo'} = 'Choix ({#count#} Choisi)';
MLI18n::gi()->{'Orderlist_Cell_aToMagnalisterSelection__selection__name'} = '{#i18n:Orderlist_Cell_aToMagnalisterSelection_selectedOrdersCountInfo#}';
MLI18n::gi()->{'Orderlist_Cell_aToMagnalisterSelection__add__name'} = 'ajouter';
MLI18n::gi()->{'Orderlist_Cell_aToMagnalisterSelection__add__values__page'} = 'Sélectionner les commandes sur cette page';
MLI18n::gi()->{'Orderlist_Cell_aToMagnalisterSelection__add__values__filter'} = 'Sélectionner toutes les commandes (filtrées)';
MLI18n::gi()->{'Orderlist_Cell_aToMagnalisterSelection__sub__name'} = 'Supprimer ';
MLI18n::gi()->{'Orderlist_Cell_aToMagnalisterSelection__sub__values__page'} = 'Désélectionner les commandes sur cette page';
MLI18n::gi()->{'Orderlist_Cell_aToMagnalisterSelection__sub__values__filter'} = 'Désélectionner les commandes (filtrées)';
MLI18n::gi()->{'Orderlist_Cell_aToMagnalisterSelection__sub__values__all'} = 'Désélectionner toutes les commandes';
