<?php
/**
 * 888888ba                 dP  .88888.                    dP
 * 88    `8b                88 d8'   `88                   88
 * 88aaaa8P' .d8888b. .d888b88 88        .d8888b. .d8888b. 88  .dP  .d8888b.
 * 88   `8b. 88ooood8 88'  `88 88   YP88 88ooood8 88'  `"" 88888"   88'  `88
 * 88     88 88.  ... 88.  .88 Y8.   .88 88.  ... 88.  ... 88  `8b. 88.  .88
 * dP     dP `88888P' `88888P8  `88888'  `88888P' `88888P' dP   `YP `88888P'
 *
 *                          m a g n a l i s t e r
 *                                      boost your Online-Shop
 *
 * -----------------------------------------------------------------------------
 * (c) 2010 - 2020 RedGecko GmbH -- http://www.redgecko.de
 *     Released under the MIT License (Expat)
 * -----------------------------------------------------------------------------
 */

/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Amazon_Orderlist_Customer_Name_Label'} = 'Nom de client';
MLI18n::gi()->{'ML_Amazon_Shippinglabel'} = 'Service Achat de l\'affranchissement';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Overview'} = 'Suivi du colis';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Upload'} = 'Demander l’achat de l’affranchissement';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Upload_Orderlist'} = 'Commande';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Upload_Form'} = 'Information sur le paquet';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Upload_Shippingmethod'} = 'Afficher le mode d\'expédition';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Upload_Summary'} = 'Résumé';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Orderlist_PurchaseDate'} = 'Délai de commande';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Orderlist_AmazonOrderID'} = 'N°  de commande Amazon';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Orderlist_ShipmentId'} = 'ID de livraison';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Orderlist_BuyerName'} = 'Client';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Orderlist_Price'} = 'Montant total';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Orderlist_CurrentStatus'} = 'Statut de commande Amazon';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Orderlist_CurrentStatus_Open'} = 'Ouvert';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Orderlist_CurrentStatus_Shipped'} = 'Envoyer';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Orderlist_CurrentStatus_Cancelled'} = 'Annuler';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Orderlist_ShippingStatus'} = 'Affranchissement réquisitionné';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Package_Length'} = 'Longueur';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Package_Width'} = 'Largeur';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Package_Height'} = 'Hauteur';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Form_Customer_Name_Label'} = 'Nom du client';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Form_ProductName'} = 'Produit';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Form_Sent'} = 'L\'article à été envoyé';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Form_Quantity'} = 'Article emballé';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Form_Shipping_Information_Label'} = 'Information d\'expédition';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Form_Package_Size_Label'} = 'Dimention du paquet';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Form_Package_Dimension_Label'} = 'Poids du paquet';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Form_Package_Carrierwillpickup_Label'} = 'Enlévement du paquet';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Form_Package_Deliveryexpierience_Label'} = 'Condition d\'expédition';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Form_Package_SenderAddress_Label'} = 'Adresse d\'expédition';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Shippingmethod_ExtraditionWarning_Label'} = 'Bon de livraisomn';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_ShippingMethod_ShippingMethodOfCutomer_Label'} = 'Mode de livraison choisi par le client.';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_ShippingMethod_Disclaimer_Label'} = 'Condition légale';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_ShippingMethod_StandardService_Label'} = 'Déterminer les options standard d\'expédition';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Summary_Statistic'} = '{1} sur {2} commande on été envoié à la place de marché.';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Receiver'} = 'Envoyé à';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_ShippingDate'} = 'Date d\'envoie';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Weight'} = 'poids';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_CarrierName'} = 'Transporteur';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_TotalPrice'} = 'Somme des frais d\'envois';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Form_CarrierName'} = 'Transporteurs';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Shippinmethod_DeliveryTime'} = 'Date de livraison estimée';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Shippinmethod_Amount'} = 'Coût';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Shippinmethod_Comment'} = 'Commentaire';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_ShippingMethod_Warning_ShippingServiceNotAvailable'} = 'Les prestataires de transport disponibles actuellement ne peuvent malheureusement pas offrir de mode d\'expédition convenable pour ces indications.';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Overview_DeleteShippingLable'} = 'Supprimer l\'étiquette';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Overview_CancelShippingLable'} = 'Annuler l\'étiquette';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Confirm'} = 'Validez et confirmez vos achats';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Download'} = 'Téléchargez les étiquettes d\'envoi';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Cancel'} = 'Annulez';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Delete'} = 'Supprimez';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Filter_Status_Default'} = 'Filtre (paiement demandé)';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Filter_Status_Full'} = 'Complètement ';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Filter_Status_Partly'} = 'partiellement';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Filter_Status_Not'} = 'Sans';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Filter_OrderType_Default'} = 'Filtre (FulfillmentChannel)';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Filter_OrderType_MFN'} = 'Standard (MFN)';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Filter_OrderType_MFNPrime'} = 'Prime par le vendeur (MFN-Prime)';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Filter_OrderType_Business'} = 'Amazon Business (B2B)';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Filter_OrderType_FBA'} = 'Expédition par Amazon (FBA)';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Filter_OrderType_Prime_SameDay'} = 'Prime Same Day';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Filter_OrderType_Prime_NextDay'} = 'Prime Next Day';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Filter_OrderType_Prime_SecondDay'} = 'Prime Second Day';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Form_Weight_Notice'} = 'Poids des articles plus le poids du matériel d\'emballage (Tare)';
MLI18n::gi()->{'ML_Amazon_Shipping_Success'} = '';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Popup_Afterconfirm_Infocontent'} = 'Votre paiement à été enregistré les étiquettes d\'expédition sont à votre disposition.<br>Pour les télécharger, cliquer sur le bouton «TÉLÉCHARGEMENT».<br> Sous la rubrique « aperçu de paquet » vous pouvez de nouveau demander des étiquettes.';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Overview_Popup_Afterconfirm_Infocontent'} = 'Votre étiquette d\'expédition est prête, pour la télécharger, cliquer sur le bouton «TÉLÉCHARGEMENT».';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Overview_CreatedDate'} = 'Affranchissement réquisitionné';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Overview_SenderAndTrackingId'} = 'Code de suivi / transporteur';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Download_Title'} = 'Télécharger les tarifs de livraison';
MLI18n::gi()->{'Orderlist_Cell_aToMagnalisterSelection_selectedOrdersCountInfo'} = 'Choix ({#count#} Choisi)';
MLI18n::gi()->{'Orderlist_Cell_aToMagnalisterSelection__selection__name'} = '{#i18n:Orderlist_Cell_aToMagnalisterSelection_selectedOrdersCountInfo#}';
MLI18n::gi()->{'Orderlist_Cell_aToMagnalisterSelection__add__name'} = 'ajouter';
MLI18n::gi()->{'Orderlist_Cell_aToMagnalisterSelection__add__values__page'} = 'Sélectionner les commandes sur cette page';
MLI18n::gi()->{'Orderlist_Cell_aToMagnalisterSelection__add__values__filter'} = 'Sélectionner toutes les commandes (filtrées)';
MLI18n::gi()->{'Orderlist_Cell_aToMagnalisterSelection__sub__name'} = 'Supprimer ';
MLI18n::gi()->{'Orderlist_Cell_aToMagnalisterSelection__sub__values__page'} = 'Désélectionner les commandes sur cette page';
MLI18n::gi()->{'Orderlist_Cell_aToMagnalisterSelection__sub__values__filter'} = 'Désélectionner les commandes (filtrées)';
MLI18n::gi()->{'Orderlist_Cell_aToMagnalisterSelection__sub__values__all'} = 'Désélectionner toutes les commandes';

// bopis
MLI18n::gi()->{'ML_Amazon_Bopis_Filter_Status_Default'} = 'Filtre (statut de la commande)';
MLI18n::gi()->{'ML_Amazon_Bopis_Filter_Store_Default'} = 'Filtre (filiale)';
MLI18n::gi()->{'ML_Amazon_Bopis_Orderlist_BuyerPhone'} = 'Numéro de téléphone du client';
MLI18n::gi()->{'ML_Amazon_Bopis_Orderlist_Deadline_Pickup'} = 'Délai de retrait';
MLI18n::gi()->{'ML_Amazon_Bopis_Orderlist_SupplySourceAlias'} = 'Nom de la filiale';
MLI18n::gi()->{'ML_Amazon_Bopis_Orderlist_Deadline_ReadyForPickup'} = 'Prêt à être retiré en';
MLI18n::gi()->{'ML_Amazon_Bopis_Orderlist_Actions'} = 'Actions';
MLI18n::gi()->{'ML_Amazon_Bopis_Orderlist_ExecuteSelectedAction'} = 'Mettre à jour l\'état de la commande';
MLI18n::gi()->{'ML_Amazon_Bopis_Orderlist_StatusDropdown'} = 'Sélectionner le statut de la commande : ';
MLI18n::gi()->{'ML_Amazon_Bopis_Orderlist_ChangeOrderStatus_Header'} = 'Modifier le statut de la commande';
MLI18n::gi()->{'ML_Amazon_Bopis_Orderlist_ChangeOrderStatus_Body'} = 'Êtes-vous sûr de vouloir changer le statut des commandes suivantes ';
MLI18n::gi()->{'ML_Amazon_Bopis_Orderlist_CancelReasonSelectorBatchUpdateLabel'} = 'Veuillez sélectionner la raison de votre annulation : ';
MLI18n::gi()->{'ML_Amazon_Bopis_Orderlist_RefundReasonSelectorBatchUpdateLabel'} = 'Veuillez sélectionner le motif de votre remboursement : ';
MLI18n::gi()->{'ML_Amazon_Bopis_Orderlist_UnprocessableOrderIdListLabel'} = 'Nous ne pouvons pas traiter les commandes suivantes (Pour plus d\'informations, survolez le(s) numéro(s) de commande avec la souris)';
MLI18n::gi()->{'ML_Amazon_Bopis_Orderlist_NewShippingStatusBatchUpdateContainerFirstPart'} = 'à';
MLI18n::gi()->{'ML_Amazon_Bopis_Orderlist_NewShippingStatusBatchUpdateContainerSecondPart'} = '';
MLI18n::gi()->{'ML_Amazon_Bopis_Orderlist_NewShippingStatusSingleUpdateContainerFirstPart'} = 'de ';
MLI18n::gi()->{'ML_Amazon_Bopis_Orderlist_NewShippingStatusSingleUpdateContainerSecondPart'} = ' à';
MLI18n::gi()->{'ML_Amazon_Bopis_Orderlist_NewShippingStatusSingleUpdateContainerThirdPart'} = '';
MLI18n::gi()->{'ML_Amazon_Bopis_Orderlist_Action_Cancel'} = 'annuler';
MLI18n::gi()->{'ML_Amazon_Bopis_Orderlist_Action_Cancelled'} = 'Annulé';
MLI18n::gi()->{'ML_Amazon_Bopis_Orderlist_Action_CancellationVerb'} = 'Annuler';
MLI18n::gi()->{'ML_Amazon_Bopis_Orderlist_Action_CancellationNoun'} = 'Annulation';
MLI18n::gi()->{'ML_Amazon_Bopis_Orderlist_Action_Refunded'} = 'Remboursé';
MLI18n::gi()->{'ML_Amazon_Bopis_Orderlist_Action_RefundVerb'} = 'Rembourser';
MLI18n::gi()->{'ML_Amazon_Bopis_Orderlist_Action_RefundNoun'} = 'Remboursement';
MLI18n::gi()->{'ML_Amazon_Bopis_Orderlist_NoInventory'} = 'Marchandise non disponible en stock';
MLI18n::gi()->{'ML_Amazon_Bopis_Orderlist_CustomerReturn'} = 'Retour du client';
MLI18n::gi()->{'ML_Amazon_Bopis_Orderlist_GeneralAdjustment'} = 'Adaptation générale';
MLI18n::gi()->{'ML_Amazon_Bopis_Orderlist_ShippingAddressUndeliverable'} = 'Adresse de livraison non livrable';
MLI18n::gi()->{'ML_Amazon_Bopis_Orderlist_CustomerExchange'} = 'Échange de clients';
MLI18n::gi()->{'ML_Amazon_Bopis_Orderlist_BuyerCanceled'} = 'Acheteur annulé';
MLI18n::gi()->{'ML_Amazon_Bopis_Orderlist_CouldNotShip'} = 'N\'a pas pu être distribué';
MLI18n::gi()->{'ML_Amazon_Bopis_Orderlist_DifferentItem'} = 'Autre produit';
MLI18n::gi()->{'ML_Amazon_Bopis_Orderlist_Abandoned'} = 'Colis non réclamé';
MLI18n::gi()->{'ML_Amazon_Bopis_Orderlist_CustomerCancel'} = 'Annulation du client';
MLI18n::gi()->{'ML_Amazon_Bopis_Orderlist_PriceError'} = 'Prix erroné';
MLI18n::gi()->{'ML_Amazon_Bopis_Orderlist_Action_TemplateHeader'} = 'Commande ';
MLI18n::gi()->{'ML_Amazon_Bopis_Orderlist_Action_TemplateBody'} = 'Veuillez sélectionner une raison pour ';
MLI18n::gi()->{'ML_Amazon_Bopis_Orderlist_Open'} = 'Ouvert';
MLI18n::gi()->{'ML_Amazon_Bopis_Orderlist_ReadyForPickup'} = 'Prêt à l\'enlèvement';
MLI18n::gi()->{'ML_Amazon_Bopis_Orderlist_PickedUp'} = 'Enlevé';
MLI18n::gi()->{'ML_Amazon_Bopis_Orderlist_RefusedPickup'} = 'Refus d\'enlèvement';
MLI18n::gi()->{'ML_Amazon_Bopis_Orderlist_Cancelled'} = 'Annulé';
MLI18n::gi()->{'ML_Amazon_Bopis_Orderlist_Refunded'} = 'Remboursé';
MLI18n::gi()->{'ML_Amazon_Bopis_OrderAlreadyCancelledHover'} = 'Cette commande a déjà été annulée';
MLI18n::gi()->{'ML_Amazon_Bopis_OrderAlreadyRefundedHover'} = 'Cette commande a déjà été remboursée';
MLI18n::gi()->{'ML_Amazon_Bopis_CantRefundOrderHover'} = 'Cette commande ne peut pas être remboursée, car elle a encore le statut \’Ouvert\'. Veuillez l\'annuler à la place.';
MLI18n::gi()->{'ML_Amazon_Bopis_CantCancelOrderHover'} = 'Cette commande ne peut pas être annulée car elle a le statut \"{#currentStatus#}\", veuillez la rembourser à la place.';
MLI18n::gi()->{'ML_Amazon_Bopis_NewShippingStatusBatchUpdateContainerCancelOrRefund'} = '
        <p style="font-weight: normal" id="allOrdersToBatchUpdateCancelOrRefund">
            Êtes-vous sûr de vouloir changer le statut des commandes suivantes 
        </p>
        <div style="display: flex" id="newShippingStatusBatchUpdateContainerCancelOrRefund">
            <p>
                à
            </p>
            <p id="newShippingStatusBatchUpdateCancelOrRefund" style="font-weight: bold; margin-left : 4px ;margin-right: 4px">
            </p>
            <p>
                ?
            </p>
        </div>

';
MLI18n::gi()->{'ML_Amazon_Bopis_NewShippingStatusBatchUpdateContainer'} = '
        <p style="font-weight: normal" id="allOrdersToBatchUpdate">
            Êtes-vous sûr de vouloir changer le statut des commandes suivantes 
        </p>
        <div style="display: flex" id="newShippingStatusBatchUpdateContainer">
            <p>
                à
            </p>
            <p id="newShippingStatusBatchUpdate" style="font-weight: bold; margin-left : 4px ;margin-right: 4px">
            </p>
            <p>
                ?
            </p>
        </div>

';
