<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'sModuleNameCrowdfox'} = 'Crowdfox';
MLI18n::gi()->{'ML_CROWDFOX_TEXT_NO_MATCHED_PRODUCTS'} = 'No items have been prepared for Crowdfox yet. You can prepare items by selecting the "Product Prepare" tab.<br>
If you miss some products you already have prepared, please check whether the products have active status, and if not, whether the configuration allows to upload inactive iems.';
MLI18n::gi()->{'crowdfox_upload_explanation'} = 'For the first upload it takes 2-3 days to see product on Crowdfox. After that it takes about 30 minutes, depending of the number added/changed products.';
MLI18n::gi()->{'crowdfox_no_gtin'} = 'Some of prepared products do not have EAN specified.';
MLI18n::gi()->{'crowdfox_label_not_matched'} = 'don\'t match';
MLI18n::gi()->{'crowdfox_label_title'} = 'Crowdfox title';
MLI18n::gi()->{'crowdfox_category'} = 'Crowdfox category';
MLI18n::gi()->{'crowdfox_label_item_id'} = 'Crowdfox item ID';
MLI18n::gi()->{'CROWDFOX_INVENTORY_INFO'} = 'To check if products uploaded successfully to Crowdfox, please log in to <a href="https://sell.crowdfox.com/login" target="_blank">Crowdfox administration page</a>.';
MLI18n::gi()->{'crowdfox_obligation_info'} = 'price per %s: %s';
