<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'CROWDFOX_ML_LABEL_ARTICLE_SKU'} = 'SKU';
MLI18n::gi()->{'CROWDFOX_ML_LABEL_ARTICLE_NAME'} = 'Crodfox Title';
MLI18n::gi()->{'CROWDFOX_ML_LABEL_ARTICLE_SHOP_PREIS'} = 'Crodfox Price';
MLI18n::gi()->{'CROWDFOX_ML_LABEL_ARTICLE_MARKETPLACE_PREIS'} = 'Marketplace Price';
MLI18n::gi()->{'CROWDFOX_ML_LABEL_ARTICLE_MARKETPLACE_QUANTITY'} = 'Quantitiy<br />Shop / Crowdfox';
MLI18n::gi()->{'crowdfox_inventory_listing_status'} = 'Status';
MLI18n::gi()->{'crowdfox_inventory_reject_message'} = 'Please contact the Crowdfox Support and ask for the reason why the product could not be listed.';
MLI18n::gi()->{'Crowdfox_Productlist_Cell_aPreparedStatus__OK__title'} = 'Successfully prepared items';
MLI18n::gi()->{'Crowdfox_Productlist_Cell_aPreparedStatus__ERROR__title'} = 'incorrect prepared items';
MLI18n::gi()->{'Crowdfox_Productlist_Cell_aPreparedStatus__OPEN__title'} = 'not checked prepared products';
MLI18n::gi()->{'Crowdfox_Productlist_Filter_aPreparedStatus__OK'} = 'successfully prepared';
MLI18n::gi()->{'Crowdfox_Productlist_Filter_aPreparedStatus__ERROR'} = 'incorrect prepared items';
MLI18n::gi()->{'Crowdfox_Productlist_Filter_aPreparedStatus__OPEN'} = 'not checked prepared products';
MLI18n::gi()->{'Crowdfox_Productlist_Cell_aPreparedType__Chinese'} = 'auction (Chinese)';
MLI18n::gi()->{'Crowdfox_Productlist_Cell_aPreparedType__FixedPriceItem'} = 'Fix-price';
MLI18n::gi()->{'Crowdfox_Productlist_Cell_aPreparedType__StoresFixedPrice'} = 'Fix price (Crowdfox Store)';
MLI18n::gi()->{'Crowdfox_Productlist_Cell_aPreparedType__apply'} = 'Create new products';
MLI18n::gi()->{'Crowdfox_Productlist_Header_sPreparedType'} = 'preparation type';
