<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'check24_config_orderimport__field__orderimport.paymentmethod__label'} = 'Mode de paiement de la commande';
MLI18n::gi()->{'check24_config_orderimport__field__orderimport.paymentmethod__help'} = 'Mode de paiement qui sera attribué à toutes les commandes Check24 lors de l\'importation des commandes. <br><br>
Vous pouvez définir d\'autres modes de paiements qui s\'afficheront dans le menu déroulant en vous rendant sur "Shopware" > "moyens de paiement".<br><br>
Ce réglage est important pour l\'impression des bons de livraison et des factures, mais aussi pour le traitement ultérieur des commandes dans votre boutique ainsi que dans votre gestion des marchandises.';
MLI18n::gi()->{'check24_config_orderimport__field__orderimport.paymentmethod__hint'} = '';
MLI18n::gi()->{'check24_config_orderimport__field__orderimport.shippingmethod__label'} = 'Mode de livraison de la commande';
MLI18n::gi()->{'check24_config_orderimport__field__orderimport.shippingmethod__help'} = '<p>Lors des importations des commandes, Check24 ne transmet pas d\'information sur le mode d\'expédition. </p>
<p>Veuillez sélectionner dans le menu déroulant, les modes de livraison de votre boutique. Vous pouvez définir les modes de livraison de votre boutique en vous rendant sur "Shopware" > "paramètres" > "Frais de port". </p>
<p>Ce réglage est important pour l\'impression des bons de livraison et des factures, mais aussi pour le traitement ultérieur des commandes dans votre boutique ainsi que dans votre gestion des marchandises.</p> ';
MLI18n::gi()->{'check24_config_orderimport__field__orderimport.shippingmethod__hint'} = '';
MLI18n::gi()->{'check24_config_orderimport__field__paymentstatus__label'} = 'Statut de paiement dans la boutique';
MLI18n::gi()->{'check24_config_orderimport__field__paymentstatus__hint'} = '';
MLI18n::gi()->{'ayn24_config_orderimport__field__customergroup__help'} = '{#i18n:global_config_orderimport_field_customergroup_help#}';
