<?php
/*
 * 888888ba                 dP  .88888.                    dP
 * 88    `8b                88 d8'   `88                   88
 * 88aaaa8P' .d8888b. .d888b88 88        .d8888b. .d8888b. 88  .dP  .d8888b.
 * 88   `8b. 88ooood8 88'  `88 88   YP88 88ooood8 88'  `"" 88888"   88'  `88
 * 88     88 88.  ... 88.  .88 Y8.   .88 88.  ... 88.  ... 88  `8b. 88.  .88
 * dP     dP `88888P' `88888P8  `88888'  `88888P' `88888P' dP   `YP `88888P'
 *
 *                          m a g n a l i s t e r
 *                                      boost your Online-Shop
 *
 * -----------------------------------------------------------------------------
 * (c) 2010 - 2020 RedGecko GmbH -- http://www.redgecko.de
 *     Released under the MIT License (Expat)
 * -----------------------------------------------------------------------------
 */

/* Autogenerated file. Do not change! */

MLI18n::gi()->{'WooCommerce_Orderimport_CountryCodeIsEmptyError'} = 'Marketplace didn’t provide the country code for order {#mpOrderId#}. Please contact the magnalister support';
MLI18n::gi()->{'WooCommerce_Orderimport_CountryCodeDontExistsError'} = 'Country code {#ISO#} doesn\'t exist in your shop so we cannot import the order {#mpOrderId#}.';
MLI18n::gi()->{'WooCommerce_Orderimport_CurrencyCodeDontExistsError'} = 'Currency code {#ISO#} doesn\'t exist in your shop so we cannot import the order {#mpOrderId#}.';
MLI18n::gi()->{'WooCommerce_Orderimport_CustomerGroup_Notloggedin'} = 'Don\'t create customer account';
MLI18n::gi()->{'global_config_orderimport_field_customergroup_help'} = 'global_config_orderimport_field_customergroup_help';
MLI18n::gi()->{'woocommerce_orderstatus_carrier_defaultField_value_shippingname'} = 'woocommerce_orderstatus_carrier_defaultField_value_shippingname';
MLI18n::gi()->{'AutomaticAllocation'} = 'Automatic Allocation';
MLI18n::gi()->{'WooCommerce_OrderImport_ThirdParty_GDPR_Error'} = 'Order {#MPOrderId#} could not be imported. An unsupported WooCommerce third party module reports: Du musst der Datenschutzerklärung zustimmen.';