<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'ebay_prepare_form__field__title__label'} = 'Product Name';
MLI18n::gi()->{'ebay_prepare_form__field__title__hint'} = 'Title, max. 80 characters';
MLI18n::gi()->{'ebay_prepare_form__field__title__optional__checkbox__labelNegativ'} = 'Always use product title from web-shop';
