<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Magento_CleanShopCacheMessage'} = 'Please clear your Magento cache. "system > cache management" push the button "flush cache storage".';
