<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Magento2_Productlist_Filter_sStatus'} = 'Statut';
MLI18n::gi()->{'Magento2_Productlist_Filter_sActive'} = 'actif';
MLI18n::gi()->{'Magento2_Productlist_Filter_sInactive'} = 'inactif';
MLI18n::gi()->{'Magento2_Productlist_Filter_sManufacturer'} = 'Fabricant';
MLI18n::gi()->{'Magento2_Productlist_Filter_sManufacturerId'} = 'Numéro de fabricant';
MLI18n::gi()->{'Magento2_Productlist_Filter_sEan'} = 'ean';
MLI18n::gi()->{'Magento2_Productlist_Filter_sCategory'} = 'Catégorie';

MLI18n::gi()->{'Magento2_Productlist_Filter_sProductType'} = 'Product type';
MLI18n::gi()->{'Magento2_Productlist_Filter_sConfigurable'} = 'Configurable';
MLI18n::gi()->{'Magento2_Productlist_Filter_sSimple'} = 'Simple';
MLI18n::gi()->{'Magento2_Productlist_Filter_sDownloadable'} = 'Downloadable';
MLI18n::gi()->{'Magento2_Productlist_Filter_sVirtual'} = 'Virtual';
