<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'bepado_prepare_form__legend__categories'} = 'Catégorie Bepado';
MLI18n::gi()->{'bepado_prepare_form__legend__shipping'} = 'Livraison';
MLI18n::gi()->{'bepado_prepare_form__legend__details'} = 'Mise en ligne de l\'offre';
MLI18n::gi()->{'bepado_prepare_form__field__b2b_price_active__label'} = 'Activer les prix B2B';
MLI18n::gi()->{'bepado_prepare_form__field__b2b_price_active__hint'} = '';
MLI18n::gi()->{'bepado_prepare_form__field__categories__label'} = 'catégorie sur la place de marché';
MLI18n::gi()->{'bepado_prepare_form__field__categories__hint'} = '';
MLI18n::gi()->{'bepado_prepare_form__field__category__label'} = 'Catégorie sur la place de marché';
MLI18n::gi()->{'bepado_prepare_form__field__category__hint'} = '';
MLI18n::gi()->{'bepado_prepare_form__field__shippingtime__label'} = 'Délais de livraison';
MLI18n::gi()->{'bepado_prepare_form__field__shippingtime__hint'} = '';
MLI18n::gi()->{'bepado_prepare_form__field__shippingcontainer__label'} = 'Frais de livraison';
MLI18n::gi()->{'bepado_prepare_form__field__shippingcountry__label'} = 'Pays d\'expédition';
MLI18n::gi()->{'bepado_prepare_form__field__shippingservice__label'} = 'Transporteur';
MLI18n::gi()->{'bepado_prepare_form__field__shippingcost__label'} = 'Frais de livraison';
