<?php
/*
 * 888888ba                 dP  .88888.                    dP
 * 88    `8b                88 d8'   `88                   88
 * 88aaaa8P' .d8888b. .d888b88 88        .d8888b. .d8888b. 88  .dP  .d8888b.
 * 88   `8b. 88ooood8 88'  `88 88   YP88 88ooood8 88'  `"" 88888"   88'  `88
 * 88     88 88.  ... 88.  .88 Y8.   .88 88.  ... 88.  ... 88  `8b. 88.  .88
 * dP     dP `88888P' `88888P8  `88888'  `88888P' `88888P' dP   `YP `88888P'
 *
 *                          m a g n a l i s t e r
 *                                      boost your Online-Shop
 *
 * -----------------------------------------------------------------------------
 * (c) 2010 - 2022 RedGecko GmbH -- http://www.redgecko.de
 *     Released under the MIT License (Expat)
 * -----------------------------------------------------------------------------
 */

/* Autogenerated file. Do not change! */

MLI18n::gi()->{'sModuleNameEbay'} = 'eBay';
MLI18n::gi()->{'sEbayNoInternationalShipping'} = 'Ne pas expédier à l\'étranger';
MLI18n::gi()->{'sEbayProductIdentifierSyncButton'} = 'Synchronisation des codes EAN et MPN vers eBay';
MLI18n::gi()->{'sEbaySyncButtonDisableIfno'} = 'Cette fonction n\'est pas disponible.';
MLI18n::gi()->{'sEbayDefaultValueText'} = 'Valeur par défaut';
MLI18n::gi()->{'ML_EBAY_N_PENDING_UPDATES_TITLE_ITEMS'} = 'Synchronisation des prix et des stocks:';
MLI18n::gi()->{'ML_EBAY_N_PENDING_UPDATES_TITLE_PRODUCTDETAILUPDATES'} = 'Attributs requis par eBay :';
MLI18n::gi()->{'ML_EBAY_PLUS_ORDER'} = 'Ceci est une commande <span style="color:#e31a1c;">eBay Plus</span>.';
MLI18n::gi()->{'ML_TEXT_WARNING'} = 'Avertissement';
MLI18n::gi()->{'ML_EBAY_PLUS_ORDER_WRONG_SHIPPING'} = 'Le mode de livraison choisit n\'est pas compatible avec eBay plus.';
MLI18n::gi()->{'eBaySalesRecordNumber'} = 'Numéro de protocole de vente';
MLI18n::gi()->{'ebay_order_detail_information_to_ebay_seller_hub'} = '<br>Cliquez sur ce <a href="%s">lien</a> pour effectuer le remboursement (partiel) de la commande via l’espace vendeur eBay.';
MLI18n::gi()->ML_EBAY_NO_BASEPRICE_FOR_VARIATIONS_WITH_DIFFERENT_BASEPRICE = 'eBay ne prend pas en charge les prix de base pour les variantes.<br>Puisque le prix de base est différent sur vos variantes, nous avons supprimé les prix de base pour l\'article (SKU : {#SKU#}).';
MLI18n::gi()->ML_EBAY_IMPORT_CATEGORIES = 'Catégorie eBay Importation';