<?php
/**
 * 888888ba                 dP  .88888.                    dP
 * 88    `8b                88 d8'   `88                   88
 * 88aaaa8P' .d8888b. .d888b88 88        .d8888b. .d8888b. 88  .dP  .d8888b.
 * 88   `8b. 88ooood8 88'  `88 88   YP88 88ooood8 88'  `"" 88888"   88'  `88
 * 88     88 88.  ... 88.  .88 Y8.   .88 88.  ... 88.  ... 88  `8b. 88.  .88
 * dP     dP `88888P' `88888P8  `88888'  `88888P' `88888P' dP   `YP `88888P'
 *
 *                          m a g n a l i s t e r
 *                                      boost your Online-Shop
 *
 * -----------------------------------------------------------------------------
 * (c) 2010 - 2020 RedGecko GmbH -- http://www.redgecko.de
 *     Released under the MIT License (Expat)
 * -----------------------------------------------------------------------------
 */

/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Ebay_Product_Matching'} = 'Appariement d\'articles';
MLI18n::gi()->{'Ebay_Productlist_Match_Manual_Button_Save'} = 'SAUVEGARDER L’APPARIEMENT ET PRÉPARER L’ARTICLE';
MLI18n::gi()->{'Ebay_Productlist_Itemsearch_Select'} = 'Sélectionnez';
MLI18n::gi()->{'Ebay_Productlist_Itemsearch_Title'} = 'Titre sur eBay';
MLI18n::gi()->{'Ebay_Productlist_Itemsearch_SkuOfManufacturer'} = 'Numéro d\'Article Fabricant';
MLI18n::gi()->{'Ebay_Productlist_Itemsearch_Barcode'} = 'Code-barres (EAN, UPC ou ISBN)';
MLI18n::gi()->{'Ebay_Productlist_Itemsearch_Epid'} = 'ePID';
MLI18n::gi()->{'Ebay_Productlist_Itemsearch_Search_Free'} = 'Nouvelle recherche';
MLI18n::gi()->{'Ebay_Productlist_Itemsearch_Search_EPID'} = 'Saisie directe ePID';
MLI18n::gi()->{'Ebay_Productlist_Itemsearch_CreateNewProduct'} = 'Demander un nouveau produit au catalogue eBay';
MLI18n::gi()->{'Ebay_Productlist_Itemsearch_DontMatch'} = 'Ne pas rattacher';
MLI18n::gi()->{'Ebay_Productlist_Itemsearch_DontMatch_Warning'} = 'Des déclinaisons sont également transmises à eBay si vous choisissez l‘option „ne pas apparier“. Nous attirons toutefois votre attention sur la distinction suivante:
<br />
<ol><li>La déclinaison produit possède un code EAN dans la boutique en ligne
<br /><br />
En ce cas, magnalister essaie d‘apparier un produit au catalogue d‘eBay avec la déclinaison. Si cette procédure aboutit, la variante est associée avec un ePID et publiée sur eBay.
<br /><br />
Si aucun produit au catalogue ne peut être clairement associé par le biais de l‘EAN, magnalister envoie une requête pour intégrer la déclinaison au catalogue d‘eBay. Une fois accaptée par eBay, elle apparaîtra automatiquement sur la place du marché.
<br /><br />
</li><li>La déclinaison du produit ne possède pas de code EAN
<br /><br />
En ce cas, il est impossible d‘apparier le produit avec un autre figurant au catalogue d‘eBay, c‘est pourquoi eBay envoie un message d‘erreur. Vous le trouverez sous l‘onglet „Inventaire“ → „Rapports d’erreurs“</li></ol>';
MLI18n::gi()->{'Ebay_Productlist_Cell_aPreparedStatus__OK__title'} = 'Préparé avec succès';
MLI18n::gi()->{'Ebay_Productlist_Cell_aPreparedStatus__ERROR__title'} = 'Mal préparé';
MLI18n::gi()->{'Ebay_Productlist_Cell_aPreparedStatus__OPEN__title'} = 'Préparation non vérifiée';
MLI18n::gi()->{'Ebay_Productlist_Filter_aPreparedStatus__OK'} = 'Préparé avec succès';
MLI18n::gi()->{'Ebay_Productlist_Filter_aPreparedStatus__ERROR'} = 'Mal préparé';
MLI18n::gi()->{'Productlist_Filter_aMarketplaceSync__notTransferred'} = 'Afficher les objets qui n\'ont pas été mis en vente sur {#marketplace#} depuis au moins un an.';
MLI18n::gi()->{'Ebay_Productlist_Cell_aPreparedType__Matched'} = 'Produit avec ePID<br /><span class="small">(Obligation de figurer au catalogue)</span>';
MLI18n::gi()->{'Ebay_Productlist_Cell_aPreparedType__NotMatched'} = 'Données propres<br /><span class="small">(Pas d‘obligation de figurer au catalogue)</span>';
MLI18n::gi()->{'Ebay_Productlist_Cell_aPreparedType__Chinese'} = 'Vente aux enchères (chinoise)';
MLI18n::gi()->{'Ebay_Productlist_Cell_aPreparedType__FixedPriceItem'} = 'Prix fixe';
MLI18n::gi()->{'Ebay_Productlist_Cell_aPreparedType__StoresFixedPrice'} = 'Prix fixe (eBay Store)';
MLI18n::gi()->{'Ebay_Productlist_Header_sPreparedListingType'} = 'Type de vente aux enchères';
MLI18n::gi()->{'Ebay_Productlist_Header_sPreparedType'} = 'Type de préparation';
MLI18n::gi()->{'Ebay_Productlist_Prepare_sResetValuesButton'} = 'Annulation partielle de la préparation';
MLI18n::gi()->{'Ebay_Productlist_Prepare_aResetValues__buttons__ok'} = 'ok';
MLI18n::gi()->{'Ebay_Productlist_Prepare_aResetValues__buttons__abort'} = 'annuler';
MLI18n::gi()->{'Ebay_Productlist_Prepare_aResetValues__checkboxes__title'} = 'Rétablir le titre par défaut';
MLI18n::gi()->{'Ebay_Productlist_Prepare_aResetValues__checkboxes__subtitle'} = 'Rétablir le sous-titre par défaut';
MLI18n::gi()->{'Ebay_Productlist_Prepare_aResetValues__checkboxes__description'} = 'Rétablir la description d\'article par défaut';
MLI18n::gi()->{'Ebay_Productlist_Prepare_aResetValues__checkboxes__pictures'} = 'Annuler la sélection d\'images';
MLI18n::gi()->{'Ebay_Productlist_Prepare_aResetValues__checkboxes__strikeprices'} = 'Rétablir les prix barrés';
MLI18n::gi()->{'Ebay_Productlist_Prepare_aResetValues__checkboxes__unprepare'} = 'Rétablir la préparation complète';
MLI18n::gi()->{'Ebay_Productlist_Matching_sResetValuesButton'} = 'Annulation partielle de la préparation';
MLI18n::gi()->{'Ebay_Productlist_Matching_aResetValues__buttons__ok'} = 'ok';
MLI18n::gi()->{'Ebay_Productlist_Matching_aResetValues__buttons__abort'} = 'annuler';
MLI18n::gi()->{'Ebay_Productlist_Matching_aResetValues__checkboxes__matching'} = 'Annulation de l\'appariement';
MLI18n::gi()->{'Ebay_Productlist_Matching_aResetValues__checkboxes__unprepare'} = 'Annulation complète de la préparation';
MLI18n::gi()->{'Ebay_Productlist_Upload_ShippingFee_Notice_Title'} = 'Information';
MLI18n::gi()->{'Ebay_Productlist_Upload_ShippingFee_Notice_Content'} = 'Selon votre contrat, eBay calcule des frais d’insertion ou des frais d\'option, telles que l\'ajout de "sous-titres".
Le transfert des produits déclenche donc des frais.
Vérifiez votre tarif eBay pour éviter d\'éventuels frais indésirables.';
