<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'ebay_config_orderimport__field__orderimport.shippingmethod__label'} = 'Shipping Service of the Orders';
MLI18n::gi()->{'ebay_config_orderimport__field__orderimport.shippingmethod__help'} = '<p>Shipping service which will be assigned to all ebay orders within the order import</p>
<p>Please choose the available shipping service from the web shop here. You can define the parameters for the drop down menu in Prestashop-admin > Shipping > carriers</p>
<p>That configuration is important for printing of the invoice and shipping documents as well as for later adaptation of the invoice in the shop and for your ERP system.</p>';
MLI18n::gi()->{'ebay_config_orderimport__field__orderimport.shippingmethod__hint'} = '';
