<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'cdiscount_config_orderimport__field__orderimport.shippingmethod__label'} = 'Mode d\'expédition de la commande';
MLI18n::gi()->{'cdiscount_config_orderimport__field__orderimport.shippingmethod__help'} = '<p>Cdiscount ne transmet pas d\'informations sur le mode d\'expédition avec l\'importation des commandes.</p>
<p>Choisissez ici les modes d\'expédition disponibles, pour votre boutique. Le contenus de la liste de choix est défini par vous-même. Pour cela, rendez-vous dans le menu Prestashop-Admin > expédition > du service d\'expédition.</p>
<p>Ce réglage est important pour l\'impression de bons de livraison et de factures et pour le traitement de la commande.</p>';
MLI18n::gi()->{'cdiscount_config_orderimport__field__orderimport.shippingmethod__hint'} = '';
