<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'bepado_prepare_form__legend__categories'} = 'Bepado category';
MLI18n::gi()->{'bepado_prepare_form__legend__shipping'} = 'shipping';
MLI18n::gi()->{'bepado_prepare_form__legend__details'} = 'Offer configurations';
MLI18n::gi()->{'bepado_prepare_form__field__b2b_price_active__label'} = 'Use B2B Price';
MLI18n::gi()->{'bepado_prepare_form__field__b2b_price_active__hint'} = '';
MLI18n::gi()->{'bepado_prepare_form__field__categories__label'} = 'Marketplace category';
MLI18n::gi()->{'bepado_prepare_form__field__categories__hint'} = '';
MLI18n::gi()->{'bepado_prepare_form__field__category__label'} = 'Marketplace category';
MLI18n::gi()->{'bepado_prepare_form__field__category__hint'} = '';
MLI18n::gi()->{'bepado_prepare_form__field__shippingtime__label'} = 'shippint time';
MLI18n::gi()->{'bepado_prepare_form__field__shippingtime__hint'} = '';
MLI18n::gi()->{'bepado_prepare_form__field__shippingcontainer__label'} = 'Shipping costs';
MLI18n::gi()->{'bepado_prepare_form__field__shippingcountry__label'} = 'shipping country';
MLI18n::gi()->{'bepado_prepare_form__field__shippingservice__label'} = 'Carrier';
MLI18n::gi()->{'bepado_prepare_form__field__shippingcost__label'} = 'Shipping costs';
