<?php
/*
 * 888888ba                 dP  .88888.                    dP
 * 88    `8b                88 d8'   `88                   88
 * 88aaaa8P' .d8888b. .d888b88 88        .d8888b. .d8888b. 88  .dP  .d8888b.
 * 88   `8b. 88ooood8 88'  `88 88   YP88 88ooood8 88'  `"" 88888"   88'  `88
 * 88     88 88.  ... 88.  .88 Y8.   .88 88.  ... 88.  ... 88  `8b. 88.  .88
 * dP     dP `88888P' `88888P8  `88888'  `88888P' `88888P' dP   `YP `88888P'
 *
 *                          m a g n a l i s t e r
 *                                      boost your Online-Shop
 *
 * -----------------------------------------------------------------------------
 * (c) 2010 - 2021 RedGecko GmbH -- http://www.redgecko.de
 *     Released under the MIT License (Expat)
 * -----------------------------------------------------------------------------
 */

MLI18n::gi()->Vendor = 'Vendor';
MLI18n::gi()->SKU = 'SKU (Stock Keeping Unit)';
MLI18n::gi()->Barcode = 'Barcode (ISBN, UPC, GTIN usw.)';
MLI18n::gi()->Description = 'Product-Description';
MLI18n::gi()->ItemName = 'Product-Title';
MLI18n::gi()->Weight = 'Weight';
MLI18n::gi()->ProductType = 'Product type';
MLI18n::gi()->{'form_config_orderimport_exchangerate_update_help'} = '
<strong>General:</strong>
<p>
If the currency set up in the web shop differs from that of the marketplace, magnalister calculates the article price with the help of an automatic currency conversion.
</p>
<strong>Caution:</strong>
<p>
For this we use the exchange rate generated by the external currency converter "alphavantage". Important: We assume no liability for the currency conversion of external services.
</p>
<p>
The following functions trigger an update of the currency exchange rate:
<ul>
<li>Order Import</li>
<li>Item Preparation</li>
<li>Item Upload</li>
<li>Stock/Price Synchronization</li>
</ul>
</p>';
MLI18n::gi()->{'form_config_orderimport_exchangerate_update_alert'} = '<strong>Caution:</strong>
<p>
By activating this function, the currency settings in your web-shop will be updated and overwritten with the current "alphavantage" exchange-rate.
<u>As a result, this will affect your foreign currency in the web-shop frontend.</u>
</p>
<p>
The following magnalister functions trigger the exchange-rate update:
<ul>
<li>Order import</li>
<li>Preparation of products</li>
<li>Upload of products</li>
<li>Synchronization of stock and prices</li>
</ul>
</p>';
MLI18n::gi()->OrderStatus_Open = 'Unfulfilled';
MLI18n::gi()->OrderStatus_Fulfilled = 'Fulfilled';
MLI18n::gi()->OrderStatus_Cancelled = 'Canceled';
MLI18n::gi()->FinancialStatus_Empty = 'Let magnalister determine whether the order is "paid" or "pending".';
MLI18n::gi()->FinancialStatus_Pending = 'Pending';
MLI18n::gi()->FinancialStatus_Authorized = 'Authorized';
MLI18n::gi()->FinancialStatus_PartiallyPaid = 'Partially paid';
MLI18n::gi()->FinancialStatus_Paid = 'Paid';
MLI18n::gi()->FinancialStatus_PartiallyRefunded = 'Partially refunded';
MLI18n::gi()->FinancialStatus_Refunded = 'Refunded';
MLI18n::gi()->FinancialStatus_Voided = 'Voided';

MLI18n::gi()->set('formfields_config_uploadInvoiceOption_help_erp', '', true);
MLI18n::gi()->set('formfields_config_uploadInvoiceOption_help_webshop', '', true);