<?php
/*
 * 888888ba                 dP  .88888.                    dP
 * 88    `8b                88 d8'   `88                   88
 * 88aaaa8P' .d8888b. .d888b88 88        .d8888b. .d8888b. 88  .dP  .d8888b.
 * 88   `8b. 88ooood8 88'  `88 88   YP88 88ooood8 88'  `"" 88888"   88'  `88
 * 88     88 88.  ... 88.  .88 Y8.   .88 88.  ... 88.  ... 88  `8b. 88.  .88
 * dP     dP `88888P' `88888P8  `88888'  `88888P' `88888P' dP   `YP `88888P'
 *
 *                          m a g n a l i s t e r
 *                                      boost your Online-Shop
 *
 * -----------------------------------------------------------------------------
 * (c) 2010 - 2023 RedGecko GmbH -- http://www.redgecko.de
 *     Released under the MIT License (Expat)
 * -----------------------------------------------------------------------------
 */

MLI18n::gi()->Vendor = 'Vendor';
MLI18n::gi()->SKU = 'SKU (Stock Keeping Unit)';
MLI18n::gi()->Barcode = 'Barcode (ISBN, UPC, GTIN usw.)';
MLI18n::gi()->Description = 'Product-Description';
MLI18n::gi()->ItemName = 'Product-Title';
MLI18n::gi()->Weight = 'Weight';
MLI18n::gi()->ProductType = 'Product type';
MLI18n::gi()->Shopify_Carrier_Other = 'Other';
MLI18n::gi()->{'form_config_orderimport_exchangerate_update_help'} = '
<strong>General:</strong>
<p>
If the currency set up in the web shop differs from that of the marketplace, magnalister calculates the article price with the help of an automatic currency conversion.
</p>
<strong>Caution:</strong>
<p>
For this we use the exchange rate generated by the external currency converter "alphavantage". Important: We assume no liability for the currency conversion of external services.
</p>
<p>
The following functions trigger an update of the currency exchange rate:
<ul>
<li>Order Import</li>
<li>Item Preparation</li>
<li>Item Upload</li>
<li>Stock/Price Synchronization</li>
</ul>
</p>';
MLI18n::gi()->{'form_config_orderimport_exchangerate_update_alert'} = '<strong>Caution:</strong>
<p>
By activating this function, the currency settings in your web-shop will be updated and overwritten with the current "alphavantage" exchange-rate.
<u>As a result, this will affect your foreign currency in the web-shop frontend.</u>
</p>
<p>
The following magnalister functions trigger the exchange-rate update:
<ul>
<li>Order import</li>
<li>Preparation of products</li>
<li>Upload of products</li>
<li>Synchronization of stock and prices</li>
</ul>
</p>';
MLI18n::gi()->OrderStatus_Open = 'Unfulfilled';
MLI18n::gi()->OrderStatus_Fulfilled = 'Fulfilled';
MLI18n::gi()->OrderStatus_Cancelled = 'Canceled';
MLI18n::gi()->FinancialStatus_Empty = 'Let magnalister determine whether the order is "paid" or "pending".';
MLI18n::gi()->FinancialStatus_Pending = 'Pending';
MLI18n::gi()->FinancialStatus_Authorized = 'Authorized';
MLI18n::gi()->FinancialStatus_PartiallyPaid = 'Partially paid';
MLI18n::gi()->FinancialStatus_Paid = 'Paid';
MLI18n::gi()->FinancialStatus_PartiallyRefunded = 'Partially refunded';
MLI18n::gi()->FinancialStatus_Refunded = 'Refunded';
MLI18n::gi()->FinancialStatus_Voided = 'Voided';
MLI18n::gi()->CustomerGroupSettingNotSupported = 'This option is not supported by Shopify.';

MLI18n::gi()->set('formfields_config_uploadInvoiceOption_help_erp', '', true);
MLI18n::gi()->set('formfields_config_uploadInvoiceOption_help_webshop', '', true);

//shopify collection vat matching
MLI18n::gi()->set('orderimport_shopify_vatmatching_label', 'VAT Matching');
MLI18n::gi()->set('orderimport_shopifyvatmatching_help', '<p>Shopify does not allow third-party apps to access tax settings. You can therefore make these settings directly in magnalister to import orders with the appropriate VAT rate.</p>
<p>To do this, match a Shopify Collection with the desired order shipping country and VAT rate. The VAT rates will be stored in the order details during the magnalister order import of Shopify products.</p>
<b>Notes:</b>
<ul>
<li>If products are assigned to multiple Shopify Collections that contain different VAT rates, only the tax rate that was matched first will be applied during the order import.</li>
<li>If the imported order cannot be matched with a magnalister tax configuration, the default VAT rate provided by the Shopify API will be applied (Example: For orders with order shipping country Germany: 19%).</li>
<li>If you select the "{#i18n:shopify_global_configuration_vat_matching_option_all#}" option in the "Shopify Collection" dropdown, you can assign a single VAT rate to all products, regardless of the collection applied by Shopify.</li>
</ul>
');

MLI18n::gi()->{'orderimport_shopify_vatmatching_collection_label'} = 'Shopify Collection';

MLI18n::gi()->{'orderimport_shopify_vatmatching_shipping_country_label'} = 'Order Shipping Country';
MLI18n::gi()->{'orderimport_shopifyvatmatching_vatrate_label'} = 'VAT in %';
MLI18n::gi()->{'shopify_global_configuration_vat_matching_option_all'} = 'All Collections';
MLI18n::gi()->{'shopify_global_configuration_vat_matching_option_all_countries'} = 'All Countries';