<?php
/**
 * 888888ba                 dP  .88888.                    dP
 * 88    `8b                88 d8'   `88                   88
 * 88aaaa8P' .d8888b. .d888b88 88        .d8888b. .d8888b. 88  .dP  .d8888b.
 * 88   `8b. 88ooood8 88'  `88 88   YP88 88ooood8 88'  `"" 88888"   88'  `88
 * 88     88 88.  ... 88.  .88 Y8.   .88 88.  ... 88.  ... 88  `8b. 88.  .88
 * dP     dP `88888P' `88888P8  `88888'  `88888P' `88888P' dP   `YP `88888P'
 *
 *                          m a g n a l i s t e r
 *                                      boost your Online-Shop
 *
 * -----------------------------------------------------------------------------
 * (c) 2010 - 2019 RedGecko GmbH -- http://www.redgecko.de
 *     Released under the MIT License (Expat)
 * -----------------------------------------------------------------------------
 */

/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Amazon_Orderlist_Customer_Name_Label'} = 'Customer Name';
MLI18n::gi()->{'ML_Amazon_Shippinglabel'} = 'Buy Shipping Services';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Overview'} = 'Overview packages';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Upload'} = 'Reguest shipping fee';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Upload_Orderlist'} = 'Orders';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Upload_Form'} = 'Package information';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Upload_Shippingmethod'} = 'Show shipping methods';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Upload_Summary'} = 'Summary';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Orderlist_PurchaseDate'} = 'Order-time';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Orderlist_AmazonOrderID'} = 'Amazon order number';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Orderlist_ShipmentId'} = 'Shipping ID';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Orderlist_BuyerName'} = 'Customer';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Orderlist_Price'} = 'Full amount';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Orderlist_CurrentStatus'} = 'Amazon order status';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Orderlist_CurrentStatus_Open'} = 'open';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Orderlist_CurrentStatus_Shipped'} = 'Sent';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Orderlist_CurrentStatus_Cancelled'} = 'Cancelled';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Orderlist_ShippingStatus'} = 'Fee requested';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Package_Length'} = 'length';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Package_Width'} = 'width';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Package_Height'} = 'height';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Form_Customer_Name_Label'} = 'Customer name';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Form_PrductName'} = 'product';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Form_Sent'} = 'Article already sent';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Form_Quantity'} = 'Article in the package';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Form_Shipping_Information_Label'} = 'Shipping information';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Form_Package_Size_Label'} = 'Package size';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Form_Package_Dimension_Label'} = 'package measures';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Form_Package_Carrierwillpickup_Label'} = 'Package pickup';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Form_Package_Deliveryexperience_Label'} = 'Shipping conditions';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Form_Package_SenderAddress_Label'} = 'shipping adress';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Shippingmethod_ExtraditionWarning_Label'} = 'Proof of deliveries';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_ShippingMethod_ShippingMethodOfCutomer_Label'} = 'shipping mode of the customer';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_ShippingMethod_Disclaimer_Label'} = 'liability inclusion';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_ShippingMethod_StandardService_Label'} = 'Set Standard service option';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Summary_Statistic'} = '{1} of {2} orders has been transfered to the marketplace';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Receiver'} = 'Shipping to';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_ShippingDate'} = 'Shipping date';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Weight'} = 'Weight';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_CarrierName'} = 'Carrier';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_UnitPrice'} = 'Basic price';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_TotalPrice'} = 'total amount of shipping costs';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Form_CarrierName'} = 'Carrier Name';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Shippinmethod_DeliveryTime'} = 'Expected date of delivery';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Shippinmethod_Amount'} = 'costs';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Shippinmethod_Comment'} = 'Comment';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_ShippingMethod_Warning_ShippingServiceNotAvailable'} = 'The actual available carrier service can’t offer a proper shipping service concerning this specifications.';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Overview_DeleteShippingLable'} = 'ML_Amazon_Shippinglabel_Overview_DeleteShippingLable';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Overview_CancelShippingLable'} = 'ML_Amazon_Shippinglabel_Overview_CancelShippingLable';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Confirm'} = 'Buy shipping fee & confirm delivery';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Download'} = 'Download shipping label';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Cancel'} = 'Cancel';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Delete'} = 'Deleted';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Filter_Status_Default'} = 'Filter (Shipping labels requested)';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Filter_Status_Full'} = 'complete';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Filter_Status_Partly'} = 'partly';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Filter_Status_Not'} = 'not';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Filter_OrderType_Default'} = 'Filter (FulfillmentChannel)';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Filter_OrderType_MFN'} = 'Standard (MFN)';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Filter_OrderType_MFNPrime'} = 'Prime by seller (MFN-Prime)';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Filter_OrderType_Business'} = 'Amazon Business (B2B)';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Filter_OrderType_FBA'} = 'Shipping by Amazon (FBA)';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Filter_OrderType_Prime_SameDay'} = 'Prime Same Day';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Filter_OrderType_Prime_NextDay'} = 'Prime Next Day';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Filter_OrderType_Prime_SecondDay'} = 'Prime Second Day';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Form_Weight_Notice'} = '(Weight of the articles packing extra)';
MLI18n::gi()->{'ML_Amazon_Shipping_Success'} = '';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Popup_Afterconfirm_Infocontent'} = 'The label for the requested shipping fees has been created.<br> To download the labels click the „DOWNLOAD“-button.<br> You can request the label again under „Overview of packages“';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Overview_Popup_Afterconfirm_Infocontent'} = 'The label for the requested shipping fees has been created.<br> To download the labels click the „DOWNLOAD“-button.<br> ';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Overview_CreatedDate'} = 'Shipping labels requested';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Overview_SenderAndTrackingId'} = 'Sender / Tracking code';
MLI18n::gi()->{'ML_Amazon_Shippinglabel_Download_Title'} = 'Download shipping fee';
MLI18n::gi()->{'Orderlist_Cell_aToMagnalisterSelection_selectedOrdersCountInfo'} = 'Selection ({#count#} selected)';
MLI18n::gi()->{'Orderlist_Cell_aToMagnalisterSelection__selection__name'} = '{#i18n:Orderlist_Cell_aToMagnalisterSelection_selectedOrdersCountInfo#}';
MLI18n::gi()->{'Orderlist_Cell_aToMagnalisterSelection__add__name'} = 'add';
MLI18n::gi()->{'Orderlist_Cell_aToMagnalisterSelection__add__values__page'} = 'choose offers of this site';
MLI18n::gi()->{'Orderlist_Cell_aToMagnalisterSelection__add__values__filter'} = 'choose all offers (filtered)';
MLI18n::gi()->{'Orderlist_Cell_aToMagnalisterSelection__sub__name'} = 'delete';
MLI18n::gi()->{'Orderlist_Cell_aToMagnalisterSelection__sub__values__page'} = 'Undo selection of this site';
MLI18n::gi()->{'Orderlist_Cell_aToMagnalisterSelection__sub__values__filter'} = 'Undo the Selection of Orders (filtered)';
MLI18n::gi()->{'Orderlist_Cell_aToMagnalisterSelection__sub__values__all'} = 'Undo the Selection of Orders';
