<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'sModuleNameDawanda'} = 'DaWanda';
MLI18n::gi()->{'dawanda_upload_explanation'} = 'The marketplace processes your data and checks for content mistakes. The article processing can last up to 24 hours.';
