<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'MeinPaket_CheckinForm__Price'} = 'Prix';
MLI18n::gi()->{'MeinPaket_CheckinForm__Amount'} = 'Quantité';
MLI18n::gi()->{'MeinPaket_CheckinForm__ShippingTime'} = 'Délais de livraisons (en jours)';
MLI18n::gi()->{'MeinPaket_CheckinForm__ShopPrice'} = 'Boutique';
MLI18n::gi()->{'MeinPaket_CheckinForm__SuggestedPrice'} = 'Calculé (selon la configuration)';
MLI18n::gi()->{'MeinPaket_CheckinForm__HitPrice'} = 'Prix hit';
MLI18n::gi()->{'MeinPaket_CheckinForm__AvailibleAmount'} = 'Disponible';
MLI18n::gi()->{'MeinPaket_CheckinForm__SuggestedAmount'} = 'Calculé (d\'après la configuration)';
