<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Meinpaket_Productlist_Cell_aPreparedStatus__OK__title'} = 'Préparés avec succès';
MLI18n::gi()->{'Meinpaket_Productlist_Cell_aPreparedStatus__ERROR__title'} = 'Mal préparés';
MLI18n::gi()->{'Meinpaket_Productlist_Cell_aPreparedStatus__OPEN__title'} = 'Préparation non vérifiée';
MLI18n::gi()->{'Meinpaket_Productlist_Filter_aPreparedStatus__OK'} = 'Préparés avec succès';
MLI18n::gi()->{'Meinpaket_Productlist_Filter_aPreparedStatus__ERROR'} = 'Mal préparés';
MLI18n::gi()->{'Meinpaket_Productlist_Filter_aPreparedStatus__OPEN'} = 'Articles préparés non vérifiés';
MLI18n::gi()->{'Meinpaket_Productlist_Cell_aPreparedType__Chinese'} = 'Vente aux enchères';
MLI18n::gi()->{'Meinpaket_Productlist_Cell_aPreparedType__FixedPriceItem'} = 'Prix fixe';
MLI18n::gi()->{'Meinpaket_Productlist_Cell_aPreparedType__StoresFixedPrice'} = 'Prix fixe (boutique Allyouneed)';
MLI18n::gi()->{'Meinpaket_Productlist_Header_sPreparedType'} = 'Format de la vente';
MLI18n::gi()->{'ML_MEINPAKET_TEXT_NO_MATCHED_PRODUCTS'} = 'Vous n\'avez pas encore préparé d\'article. Afin de télécharger des articles sur la place de marché, les articles doivent d\'abord être préparés dans l\'onglet "préparer les articles".<br>
Si vous ne retrouvez pas les articles que vous avez préparé dans cet onglet, veuillez vérifier vos configurations et le statut de l\'article dans votre boutique (actif / inactif).';
