<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'sModuleNameCrowdfox'} = 'sModuleNameCrowdfox';
MLI18n::gi()->{'ML_CROWDFOX_TEXT_NO_MATCHED_PRODUCTS'} = 'ML_CROWDFOX_TEXT_NO_MATCHED_PRODUCTS';
MLI18n::gi()->{'crowdfox_upload_explanation'} = 'crowdfox_upload_explanation';
MLI18n::gi()->{'crowdfox_no_gtin'} = 'crowdfox_no_gtin';
MLI18n::gi()->{'crowdfox_label_not_matched'} = 'crowdfox_label_not_matched';
MLI18n::gi()->{'crowdfox_label_title'} = 'crowdfox_label_title';
MLI18n::gi()->{'crowdfox_category'} = 'crowdfox_category';
MLI18n::gi()->{'crowdfox_label_item_id'} = 'crowdfox_label_item_id';
MLI18n::gi()->{'CROWDFOX_INVENTORY_INFO'} = 'CROWDFOX_INVENTORY_INFO';
MLI18n::gi()->{'crowdfox_obligation_info'} = 'crowdfox_obligation_info';
