<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'CROWDFOX_ML_LABEL_ARTICLE_SKU'} = 'CROWDFOX_ML_LABEL_ARTICLE_SKU';
MLI18n::gi()->{'CROWDFOX_ML_LABEL_ARTICLE_NAME'} = 'CROWDFOX_ML_LABEL_ARTICLE_NAME';
MLI18n::gi()->{'CROWDFOX_ML_LABEL_ARTICLE_SHOP_PREIS'} = 'CROWDFOX_ML_LABEL_ARTICLE_SHOP_PREIS';
MLI18n::gi()->{'CROWDFOX_ML_LABEL_ARTICLE_MARKETPLACE_PREIS'} = 'CROWDFOX_ML_LABEL_ARTICLE_MARKETPLACE_PREIS';
MLI18n::gi()->{'CROWDFOX_ML_LABEL_ARTICLE_MARKETPLACE_QUANTITY'} = 'CROWDFOX_ML_LABEL_ARTICLE_MARKETPLACE_QUANTITY';
MLI18n::gi()->{'crowdfox_inventory_listing_status'} = 'crowdfox_inventory_listing_status';
MLI18n::gi()->{'crowdfox_inventory_reject_message'} = 'crowdfox_inventory_reject_message';
MLI18n::gi()->{'Crowdfox_Productlist_Cell_aPreparedStatus__OK__title'} = 'Crowdfox_Productlist_Cell_aPreparedStatus__OK__title';
MLI18n::gi()->{'Crowdfox_Productlist_Cell_aPreparedStatus__ERROR__title'} = 'Crowdfox_Productlist_Cell_aPreparedStatus__ERROR__title';
MLI18n::gi()->{'Crowdfox_Productlist_Cell_aPreparedStatus__OPEN__title'} = 'Crowdfox_Productlist_Cell_aPreparedStatus__OPEN__title';
MLI18n::gi()->{'Crowdfox_Productlist_Filter_aPreparedStatus__OK'} = 'Crowdfox_Productlist_Filter_aPreparedStatus__OK';
MLI18n::gi()->{'Crowdfox_Productlist_Filter_aPreparedStatus__ERROR'} = 'Crowdfox_Productlist_Filter_aPreparedStatus__ERROR';
MLI18n::gi()->{'Crowdfox_Productlist_Filter_aPreparedStatus__OPEN'} = 'Crowdfox_Productlist_Filter_aPreparedStatus__OPEN';
MLI18n::gi()->{'Crowdfox_Productlist_Cell_aPreparedType__Chinese'} = 'Crowdfox_Productlist_Cell_aPreparedType__Chinese';
MLI18n::gi()->{'Crowdfox_Productlist_Cell_aPreparedType__FixedPriceItem'} = 'Crowdfox_Productlist_Cell_aPreparedType__FixedPriceItem';
MLI18n::gi()->{'Crowdfox_Productlist_Cell_aPreparedType__StoresFixedPrice'} = 'Crowdfox_Productlist_Cell_aPreparedType__StoresFixedPrice';
MLI18n::gi()->{'Crowdfox_Productlist_Cell_aPreparedType__apply'} = 'Crowdfox_Productlist_Cell_aPreparedType__apply';
MLI18n::gi()->{'Crowdfox_Productlist_Header_sPreparedType'} = 'Crowdfox_Productlist_Header_sPreparedType';
