<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'ML_GENERIC_QTY'} = 'Quantité';
MLI18n::gi()->{'ML_GENERIC_ITEM'} = 'Article';
MLI18n::gi()->{'ML_GENERIC_EACH'} = 'Prix unitaire';
MLI18n::gi()->{'ML_GENERIC_TOTAL'} = 'Prix total';
