<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'hood_config_producttemplate__field__template.name__label'} = 'Template Product name';
MLI18n::gi()->{'hood_config_producttemplate__field__template.name__help'} = '<dl> <dt>Product name on hood</dt> <dd>The name of the product on hood. The placeholder <b>#TITLE#</b> will be replaced by the product name from the shop.</dd> </dl>';
