<?php
/**
 * 888888ba                 dP  .88888.                    dP
 * 88    `8b                88 d8'   `88                   88
 * 88aaaa8P' .d8888b. .d888b88 88        .d8888b. .d8888b. 88  .dP  .d8888b.
 * 88   `8b. 88ooood8 88'  `88 88   YP88 88ooood8 88'  `"" 88888"   88'  `88
 * 88     88 88.  ... 88.  .88 Y8.   .88 88.  ... 88.  ... 88  `8b. 88.  .88
 * dP     dP `88888P' `88888P8  `88888'  `88888P' `88888P' dP   `YP `88888P'
 *
 *                          m a g n a l i s t e r
 *                                      boost your Online-Shop
 *
 * -----------------------------------------------------------------------------
 * (c) 2010 - 2019 RedGecko GmbH -- http://www.redgecko.de
 *     Released under the MIT License (Expat)
 * -----------------------------------------------------------------------------
 */

/* Autogenerated file. Do not change! */

MLI18n::gi()->{'sModuleNameHitmeister'} = 'Kaufland.de';
MLI18n::gi()->{'hitmeister_label_title'} = 'Kaufland.de Title';
MLI18n::gi()->{'hitmeister_category'} = 'Kaufland.de Category';
MLI18n::gi()->{'hitmeister_label_item_id'} = 'Item ID';
MLI18n::gi()->{'hitmeister_search_by_title'} = 'Search by title';
MLI18n::gi()->{'hitmeister_search_by_ean'} = 'Search by ean';
MLI18n::gi()->{'hitmeister_label_not_matched'} = 'dont match';
MLI18n::gi()->{'hitmeister_upload_explanation'} = 'Uploaded articles which has an EAN known by Kaufland.de will usually be listed within an hour on Kaufland.de.
<br /><br />
EAN-articles that are not already listet on Kaufland.de will be transferred every night starting midnight by magnalister.
<br /><br />
Data will be checked and processed manually by Kaufland.de for quality control reasons. The processing can take up to 2 to 4 working days. You can check the status in your Kaufland.de administration.';
