<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Ayn24_Productlist_Cell_aPreparedStatus__OK__title'} = 'Prepared Status: Complete';
MLI18n::gi()->{'Ayn24_Productlist_Cell_aPreparedStatus__ERROR__title'} = 'Prepared Status: Error';
MLI18n::gi()->{'Ayn24_Productlist_Cell_aPreparedStatus__OPEN__title'} = 'Prepared Status: Open';
MLI18n::gi()->{'Ayn24_Productlist_Filter_aPreparedStatus__OK'} = 'Prepared Status: Complete';
MLI18n::gi()->{'Ayn24_Productlist_Filter_aPreparedStatus__ERROR'} = 'Prepared Status: Error';
MLI18n::gi()->{'Ayn24_Productlist_Filter_aPreparedStatus__OPEN'} = 'Prepared Status: Open';
MLI18n::gi()->{'Ayn24_Productlist_Cell_aPreparedType__Chinese'} = 'Chinese auction';
MLI18n::gi()->{'Ayn24_Productlist_Cell_aPreparedType__FixedPriceItem'} = 'Fixed price';
MLI18n::gi()->{'Ayn24_Productlist_Cell_aPreparedType__StoresFixedPrice'} = 'Fixed price (Ayn24 Store)';
MLI18n::gi()->{'Ayn24_Productlist_Header_sPreparedType'} = 'Type of Auction';
MLI18n::gi()->{'ML_AYN24_TEXT_NO_MATCHED_PRODUCTS'} = 'No items have been prepared for Ayn24 yet. You can prepare items by selecting the "Product Prepare" tab.<br>
If you miss some products you already have prepared, please check whether the products have active status, and if not, whether the configuration allows to upload inactive iems.';
