<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'cdiscount_config_orderimport__field__orderimport.shippingmethod__label'} = 'Shipping Service of the Orders';
MLI18n::gi()->{'cdiscount_config_orderimport__field__orderimport.shippingmethod__help'} = '<p>Cdiscount does not pass shipping service information with the order import</p>
<p>For this reason please choose the available dispatch type information from the web-shop. You can find those in the dropdown menu in Prestashop-Admin > Shipping > carriers.</p>
<p>That configuration is important for printing of the invoice and shipping documents as well as for later adaptation of the invoice in the shop and for your ERP system.</p>';
MLI18n::gi()->{'cdiscount_config_orderimport__field__orderimport.shippingmethod__hint'} = '';
