<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'hood_config_orderimport__field__orderimport.paymentstatus__label'} = 'hood_config_orderimport__field__orderimport.paymentstatus__label';
MLI18n::gi()->{'hood_config_orderimport__field__orderimport.paymentstatus__help'} = 'hood_config_orderimport__field__orderimport.paymentstatus__help';
MLI18n::gi()->{'hood_config_producttemplate_content'} = 'hood_config_producttemplate_content';
MLI18n::gi()->{'hood_config_orderimport__field__updateablepaymentstatus__label'} = 'hood_config_orderimport__field__updateablepaymentstatus__label';
MLI18n::gi()->{'hood_config_orderimport__field__updateablepaymentstatus__help'} = 'hood_config_orderimport__field__updateablepaymentstatus__help';
MLI18n::gi()->{'hood_config_orderimport__field__paidstatus__label'} = 'hood_config_orderimport__field__paidstatus__label';
MLI18n::gi()->{'hood_config_orderimport__field__paidstatus__help'} = 'hood_config_orderimport__field__paidstatus__help';
MLI18n::gi()->{'hood_config_orderimport__field__orderstatus.paid__label'} = 'hood_config_orderimport__field__orderstatus.paid__label';
MLI18n::gi()->{'hood_config_orderimport__field__orderstatus.paid__help'} = '';
MLI18n::gi()->{'hood_config_orderimport__field__paymentstatus.paid__label'} = 'hood_config_orderimport__field__paymentstatus.paid__label';
MLI18n::gi()->{'hood_config_orderimport__field__paymentstatus.paid__help'} = '';
MLI18n::gi()->{'hood_config_orderimport__field__updateable.paymentstatus__label'} = '';
MLI18n::gi()->{'hood_config_orderimport__field__updateable.paymentstatus__help'} = '';
MLI18n::gi()->{'hood_config_orderimport__field__update.paymentstatus__label'} = 'hood_config_orderimport__field__update.paymentstatus__label';
MLI18n::gi()->{'hood_config_orderimport__field__orderimport.paymentmethod__label'} = 'hood_config_orderimport__field__orderimport.paymentmethod__label';
MLI18n::gi()->{'hood_config_orderimport__field__orderimport.paymentmethod__help'} = 'hood_config_orderimport__field__orderimport.paymentmethod__help';
MLI18n::gi()->{'hood_config_orderimport__field__orderimport.paymentmethod__hint'} = '';
MLI18n::gi()->{'hood_config_orderimport__field__orderimport.shippingmethod__label'} = 'hood_config_orderimport__field__orderimport.shippingmethod__label';
MLI18n::gi()->{'hood_config_orderimport__field__orderimport.shippingmethod__help'} = 'hood_config_orderimport__field__orderimport.shippingmethod__help';
MLI18n::gi()->{'hood_config_orderimport__field__orderimport.shippingmethod__hint'} = '';
MLI18n::gi()->{'hood_config_producttemplate__field__template.content__label'} = 'hood_config_producttemplate__field__template.content__label';
MLI18n::gi()->{'hood_config_producttemplate__field__template.content__hint'} = 'hood_config_producttemplate__field__template.content__hint';
