<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'hood_prepare_form__field__description__label'} = 'hood_prepare_form__field__description__label';
MLI18n::gi()->{'hood_prepare_form__field__description__hint'} = 'hood_prepare_form__field__description__hint';
MLI18n::gi()->{'hood_prepare_form__field__description__optional__checkbox__labelNegativ'} = 'hood_prepare_form__field__description__optional__checkbox__labelNegativ';
