<?php
MLFilesystem::gi()->loadClass('Shopify_Controller_Frontend_Do_ShopifyProductCollectionCache');
class ML_Shopify_Controller_Do_ShopifyProductCollectionCache extends ML_Shopify_Controller_Frontend_Do_ShopifyProductCollectionCache {
}
