<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'ML_MESSAGE_BEFORE_UPDATE_TITLE'} = 'Mise à jour de magnalister';
MLI18n::gi()->{'ML_MESSAGE_BEFORE_UPDATE_TEXT'} = 'La mise à jour de magnalister est actuellement en cours. Le processus dure 1 à 3 minutes.';
MLI18n::gi()->{'ML_MESSAGE_BEFORE_UPDATE_TEXT'} = 'La mise à jour de magnalister est actuellement en cours. Le processus dure 1 à 3 minutes.';
MLI18n::gi()->{'ML_MESSAGE_BEFORE_UPDATE_TITLE'} = 'Mise à jour de magnalister';
