<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'priceminister_config_orderimport__field__paymentstatus__label'} = 'Statut de la commande dans votre boutique';
MLI18n::gi()->{'priceminister_config_orderimport__field__paymentstatus__hint'} = '';
MLI18n::gi()->{'priceminister_config_orderimport__field__customergroup__help'} = '{#i18n:global_config_orderimport_field_customergroup_help#}';
