<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Tradoria_Productlist_Cell_aPreparedStatus__OK__title'} = 'Préparés avec succès';
MLI18n::gi()->{'Tradoria_Productlist_Cell_aPreparedStatus__ERROR__title'} = 'Mal préparés';
MLI18n::gi()->{'Tradoria_Productlist_Cell_aPreparedStatus__OPEN__title'} = 'Préparation non vérifiée';
MLI18n::gi()->{'Tradoria_Productlist_Filter_aPreparedStatus__OK'} = 'Préparés avec succès';
MLI18n::gi()->{'Tradoria_Productlist_Filter_aPreparedStatus__ERROR'} = 'Mal préparés';
MLI18n::gi()->{'Tradoria_Productlist_Filter_aPreparedStatus__OPEN'} = 'Articles préparés non vérifiés';
