<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Tradoria_CheckinForm__Price'} = 'Prix';
MLI18n::gi()->{'Tradoria_CheckinForm__Amount'} = 'Unités';
MLI18n::gi()->{'Tradoria_CheckinForm__ShippingTime'} = 'Livraison (en jours)';
MLI18n::gi()->{'Tradoria_CheckinForm__ShopPrice'} = 'Boutique';
MLI18n::gi()->{'Tradoria_CheckinForm__SuggestedPrice'} = 'Calculé (D\'après la configuration)';
MLI18n::gi()->{'Tradoria_CheckinForm__HitPrice'} = 'Prix hit';
MLI18n::gi()->{'Tradoria_CheckinForm__AvailibleAmount'} = 'Disponible';
MLI18n::gi()->{'Tradoria_CheckinForm__SuggestedAmount'} = 'Calculé (d\'après la configuration)';
