<?php
MLFilesystem::gi()->loadClass('ShopwareCloud_Controller_Frontend_Do_ShopwareCloudCategoryCache');
class ML_ShopwareCloud_Controller_Do_ShopwareCloudCategoryCache extends ML_ShopwareCloud_Controller_Frontend_Do_ShopwareCloudCategoryCache {
}
