<?php
MLFilesystem::gi()->loadClass('ShopwareCloud_Controller_Frontend_Do_ShopwareCloudCustomerGroupCache');

class ML_ShopwareCloud_Controller_Do_ShopwareCloudCustomerGroupCache extends ML_ShopwareCloud_Controller_Frontend_Do_ShopwareCloudCustomerGroupCache {
}
