<?php
MLFilesystem::gi()->loadClass('ShopwareCloud_Controller_Frontend_Do_ShopwareCloudShippingMethodCache');

class ML_ShopwareCloud_Controller_Do_ShopwareCloudShippingMethodCache extends ML_ShopwareCloud_Controller_Frontend_Do_ShopwareCloudShippingMethodCache {
}
