<?php
MLFilesystem::gi()->loadClass('ShopwareCloud_Controller_Frontend_Do_ShopwareCloudTaxRuleCache');

class ML_ShopwareCloud_Controller_Do_ShopwareCloudTaxRuleCache extends ML_ShopwareCloud_Controller_Frontend_Do_ShopwareCloudTaxRuleCache {
}
