<?php
MLFilesystem::gi()->loadClass('ShopwareCloud_Controller_Frontend_Do_ShopwareCloudCurrencyCache');
class ML_ShopwareCloud_Controller_Do_ShopwareCloudCurrencyCache extends ML_ShopwareCloud_Controller_Frontend_Do_ShopwareCloudCurrencyCache {
}
