<?php
MLFilesystem::gi()->loadClass('ShopwareCloud_Controller_Frontend_Do_ShopwareCloudPropertyGroupCache');
class ML_ShopwareCloud_Controller_Do_ShopwareCloudPropertyGroupCache extends ML_ShopwareCloud_Controller_Frontend_Do_ShopwareCloudPropertyGroupCache {
}
