<?php
MLFilesystem::gi()->loadClass('ShopwareCloud_Controller_Frontend_Do_ShopwareCloudUnitCache');
class ML_ShopwareCloud_Controller_Do_ShopwareCloudUnitCache extends ML_ShopwareCloud_Controller_Frontend_Do_ShopwareCloudUnitCache {
}
