<?php
MLFilesystem::gi()->loadClass('ShopwareCloud_Controller_Frontend_Do_ShopwareCloudCustomFieldsCache');
class ML_ShopwareCloud_Controller_Do_ShopwareCloudCustomFieldsCache extends ML_ShopwareCloud_Controller_Frontend_Do_ShopwareCloudCustomFieldsCache {
}
