<?php
MLFilesystem::gi()->loadClass('ShopwareCloud_Controller_Frontend_Do_ShopwareCloudStateMachineStateCache');

class ML_ShopwareCloud_Controller_Do_ShopwareCloudStateMachineStateCache extends ML_ShopwareCloud_Controller_Frontend_Do_ShopwareCloudStateMachineStateCache {
}
