<?php
MLFilesystem::gi()->loadClass('ShopwareCloud_Controller_Frontend_Do_ShopwareCloudCountryCache');
class ML_ShopwareCloud_Controller_Do_ShopwareCloudCountryCache extends ML_ShopwareCloud_Controller_Frontend_Do_ShopwareCloudCountryCache {
}
