<?php
MLFilesystem::gi()->loadClass('ShopwareCloud_Controller_Frontend_Do_ShopwareCloudProductCache');
class ML_ShopwareCloud_Controller_Do_ShopwareCloudProductCache extends ML_ShopwareCloud_Controller_Frontend_Do_ShopwareCloudProductCache {
}
