<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'tradoria_config_orderimport__field__orderimport.paymentmethod__label'} = 'Mode de paiement de la commande';
MLI18n::gi()->{'tradoria_config_orderimport__field__orderimport.paymentmethod__help'} = 'Mode de paiement qui sera attribué à toutes les commandes effectuées sur Rakuten lors de l\'importation des commandes. <br><br>
Vous pouvez définir d\'autres modes de paiements qui s\'afficheront dans le menu déroulant en vous rendant sur "Shopify" > "moyens de paiement".<br><br>
Ce réglage est important pour l\'impression des bons de livraison et des factures, mais aussi pour le traitement ultérieur des commandes dans votre boutique ainsi que dans votre gestion des marchandises.';
MLI18n::gi()->{'tradoria_config_orderimport__field__orderimport.paymentmethod__hint'} = '';
MLI18n::gi()->{'tradoria_config_orderimport__field__orderimport.shippingmethod__label'} = 'Mode de livraison de la commande';
MLI18n::gi()->{'tradoria_config_orderimport__field__orderimport.shippingmethod__help'} = 'Mode de livraison qui sera attribué à toutes les commandes effectuées sur Rakuten lors de l\'importation des commandes. <br><br>
Vous pouvez définir d\'autres modes de livraison qui s\'afficheront dans le menu déroulant en vous rendant sur "Shopify" > "Paramètres" > "Frais de port".<br><br>
Ce réglage est important pour l\'impression des bons de livraison et des factures, mais aussi pour le traitement ultérieur des commandes dans votre boutique ainsi que dans votre gestion des marchandises.';
MLI18n::gi()->{'tradoria_config_orderimport__field__orderimport.shippingmethod__hint'} = '';
MLI18n::gi()->{'tradoria_config_orderimport__field__orderimport.paymentstatus__label'} = 'Statut de paiement dans votre boutique';
MLI18n::gi()->{'tradoria_config_orderimport__field__orderimport.paymentstatus__hint'} = '';
MLI18n::gi()->{'tradoria_config_orderimport__field__customergroup__help'} = '{#i18n:global_config_orderimport_field_customergroup_help#}';
