<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'hood_config_producttemplate__field__template.name__label'} = 'hood_config_producttemplate__field__template.name__label';
MLI18n::gi()->{'hood_config_producttemplate__field__template.name__help'} = 'hood_config_producttemplate__field__template.name__help';
