<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'hood_prepare_form__field__title__label'} = 'hood_prepare_form__field__title__label';
MLI18n::gi()->{'hood_prepare_form__field__title__hint'} = 'hood_prepare_form__field__title__hint';
MLI18n::gi()->{'hood_prepare_form__field__title__optional__checkbox__labelNegativ'} = 'hood_prepare_form__field__title__optional__checkbox__labelNegativ';
