<?php
/*
 * 888888ba                 dP  .88888.                    dP
 * 88    `8b                88 d8'   `88                   88
 * 88aaaa8P' .d8888b. .d888b88 88        .d8888b. .d8888b. 88  .dP  .d8888b.
 * 88   `8b. 88ooood8 88'  `88 88   YP88 88ooood8 88'  `"" 88888"   88'  `88
 * 88     88 88.  ... 88.  .88 Y8.   .88 88.  ... 88.  ... 88  `8b. 88.  .88
 * dP     dP `88888P' `88888P8  `88888'  `88888P' `88888P' dP   `YP `88888P'
 *
 *                          m a g n a l i s t e r
 *                                      boost your Online-Shop
 *
 * -----------------------------------------------------------------------------
 * (c) 2010 - 2020 RedGecko GmbH -- http://www.redgecko.de
 *     Released under the MIT License (Expat)
 * -----------------------------------------------------------------------------
 */

/* Autogenerated file. Do not change! */

MLI18n::gi()->{'WooCommerce_Orderimport_CountryCodeIsEmptyError'} = 'Le code d\'identification de pays pour la commande {#mpOrderId#} n\'a pas été fournie par la place de marché. Veuillez contacter le service client magnalister.';
MLI18n::gi()->{'WooCommerce_Orderimport_CountryCodeDontExistsError'} = 'La commande {#mpOrderId#} requiert le code d\'identification de pays {#ISO#} dans les Paramètres de votre boutique, pour pouvoir importer la commande.';
MLI18n::gi()->{'WooCommerce_Orderimport_CurrencyCodeDontExistsError'} = 'La commande {#mpOrderId#} requiert la devise{#ISO#} dans les Paramètres de votre boutique, pour pouvoir importer la commande.';
MLI18n::gi()->{'WooCommerce_Orderimport_CustomerGroup_Notloggedin'} = 'Ne pas créer de compte client';
MLI18n::gi()->{'global_config_orderimport_field_customergroup_help'} = 'Choisissez les groupes dans lesquels vos clients peuvent être classés.';
MLI18n::gi()->{'woocommerce_orderstatus_carrier_defaultField_value_shippingname'} = 'Transmetre le nom du livreur en tant que mode de livraison';
MLI18n::gi()->AutomaticAllocation = 'Attribution automatique';
MLI18n::gi()->{'WooCommerce_OrderImport_ThirdParty_GDPR_Error'} = 'L\'ordre {#MPOrderId#} ne pouvait pas être importé. Un module tiers de WooCommerce non supporté rapporte: Du musst der Datenschutzerklärung zustimmen.';