<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'WooCommerce_Productlist_Filter_sStatus'} = 'Statut';
MLI18n::gi()->{'WooCommerce_Productlist_Filter_sActive'} = 'actif';
MLI18n::gi()->{'WooCommerce_Productlist_Filter_sInactive'} = 'inactif';
MLI18n::gi()->{'WooCommerce_Productlist_Filter_sManufacturer'} = 'Fabricant';
MLI18n::gi()->{'WooCommerce_Productlist_Filter_sManufacturerId'} = 'Numéro de fabricant';
MLI18n::gi()->{'WooCommerce_Productlist_Filter_sEan'} = 'ean';
MLI18n::gi()->{'WooCommerce_Productlist_Filter_sCategory'} = 'Catégorie';

MLI18n::gi()->WooCommerce_Product_Attributes_Title = 'Titre du produit';
MLI18n::gi()->WooCommerce_Product_Attributes_ItemNumber = 'UGS';
MLI18n::gi()->WooCommerce_Product_Attributes_Description = 'Description du produit';
MLI18n::gi()->WooCommerce_Product_Attributes_Short_Description = 'Description courte du produit';
MLI18n::gi()->WooCommerce_Product_Attributes_Weight = 'Poids';
MLI18n::gi()->WooCommerce_Product_Attributes_Width = 'Longueur';
MLI18n::gi()->WooCommerce_Product_Attributes_Height = 'Largeur';
MLI18n::gi()->WooCommerce_Product_Attributes_Length = 'Hauteur';

MLI18n::gi()->WooCommerce_Product_Attributes_Keywords = 'Étiquettes produit';
