<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'FreeTextAttributesOptGroup'} = 'Additional fields';
MLI18n::gi()->{'ProductName'} = 'Title';
MLI18n::gi()->{'ProductNumber'} = 'Product number';
MLI18n::gi()->{'Description'} = 'Description';
MLI18n::gi()->{'EAN'} = 'EAN';
MLI18n::gi()->{'Weight'} = 'Weight';
MLI18n::gi()->{'Width'} = 'Width';
MLI18n::gi()->{'Height'} = 'Height';
MLI18n::gi()->{'Length'} = 'Length';
MLI18n::gi()->{'ManufacturerId'} = 'Manufacturer';
MLI18n::gi()->{'ManufacturerNumber'} = 'Manufacturer product number ';
MLI18n::gi()->{'magento2_configform_orderimport_shipping_values__matching__title'} = 'Automatic allocation';
MLI18n::gi()->set('ML_AMAZON_ERROR_CURRENCY_NOT_IN_SHOP', 'The currency (%s) associated with Amazon Marketplace is not configured in this Magento.
             Please configure the currency in "Adobe Commerce/Magento Admin > Stores > Configuration > Currency Setup > Allowed Currencies" to upload products to Amazon.', true);
MLI18n::gi()->{'ML_MAGENTO2_ERROR_CURRENCY_NO_RATE'} = 'Please configure the currency rate for (%s) in "Adobe Commerce/Magento Admin > Stores > Currency Rates."';
