<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Magento2_Orderimport_CountryCodeIsEmptyError'} = 'Marketplace didn’t provide the country code for order {#mpOrderId#}. Please contact the magnalister support';
MLI18n::gi()->{'Magento2_Orderimport_CountryCodeDontExistsError'} = 'Country code {#ISO#} doesn\'t exist in your shop so we cannot import the order {#mpOrderId#}.';
MLI18n::gi()->{'shopware_orderstatus_carrier_defaultField_value_shippingname'} = 'Pass shipping method as carrier';
