<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Magento2_Productlist_Filter_sStatus'} = 'Status';
MLI18n::gi()->{'Magento2_Productlist_Filter_sActive'} = 'active';
MLI18n::gi()->{'Magento2_Productlist_Filter_sInactive'} = 'inactive';
MLI18n::gi()->{'Magento2_Productlist_Filter_sManufacturer'} = 'Manufacturer';
MLI18n::gi()->{'Magento2_Productlist_Filter_sManufacturerId'} = 'Manufacturer part number';
MLI18n::gi()->{'Magento2_Productlist_Filter_sEan'} = 'EAN';
MLI18n::gi()->{'Magento2_Productlist_Filter_sCategory'} = 'Category';

MLI18n::gi()->{'Magento2_Productlist_Filter_sProductType'} = 'Product type';
MLI18n::gi()->{'Magento2_Productlist_Filter_sConfigurable'} = 'Configurable';
MLI18n::gi()->{'Magento2_Productlist_Filter_sSimple'} = 'Simple';
MLI18n::gi()->{'Magento2_Productlist_Filter_sDownloadable'} = 'Downloadable';
MLI18n::gi()->{'Magento2_Productlist_Filter_sVirtual'} = 'Virtual';
