<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'sModuleNameDawanda'} = 'DaWanda';
MLI18n::gi()->{'dawanda_upload_explanation'} = 'La place de marché traite à présent vos données et vérifie leurs véracité. Le traitement des articles peut durer jusqu\'à 24 heures. ';
