<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'hood_config_producttemplate__field__template.name__label'} = 'Template produit';
MLI18n::gi()->{'hood_config_producttemplate__field__template.name__help'} = '<dl>
						<dt>Nom du produit sur hood </dt>
<dd>Saisissez dans ce champ le nom de l’article, tel que vous voulez qu’il apparaisse sur votre page hood. <br>
Le champ <b>#TITLE#</b> sera automatiquement remplacé par le nom que vous avez saisi.</dd>
			</dl>';
