<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'sAddAewShopAttributeInstruction'} = '<strong>Important :  </strong><br /><br />
Pour que les données de listes soient prises en compte sur "magnalister" > "Configuration générale" > "propriétés du produit", de façon à apparier les valeurs aux attributs de la boutique, rendez vous sous Magento > "catalogue" > "attributs" pour gérer les attributs.
	<ul>
        <li>Numéro de référence fabricant(MPN)</li>
	<li>EAN</li>
    <li>Fabricant *¹</li>
        </ul><br />
*¹ <font color="green" >Les données fabricant peuvent être configurées différemment sous “magnalister” > “hood” > “Configuration” > “Préparation de l\'article” > “Marque”.</font>        
 ';
